/**
 * Primal Instinct — append call outcome to transcript filenames.
 *
 * Generated by src/build_rename_manifest.py. 5 files.
 *
 * HOW TO RUN
 *   1. script.google.com  →  New project
 *   2. Paste this whole file, replacing the default contents
 *   3. Run `dryRun` first. It logs every change WITHOUT touching anything.
 *   4. Read the log. If it looks right, run `applyRenames`.
 *   5. To undo, run `revertRenames`.
 *
 * You must be signed in as an account with edit rights on the transcripts
 * folder. The files are owned by info@primalinstinct.net — if you only have
 * view access, ask them to run it instead.
 *
 * Safe to re-run: files already carrying the suffix are skipped.
 */

var RENAMES = [
  {
    "id": "1H2rnT1PMyGVGzAtNlz_g84tRnyAcCkov",
    "from": "05/14/2026 - Tristian Clunis & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/14/2026 - Tristian Clunis & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1MqyayoUsI10YoLb9AO4ICAFk7SDzm4r4",
    "from": "06/09/2026 - Badrane Hriouch x Harry Edmonds KL",
    "to": "06/09/2026 - Badrane Hriouch x Harry Edmonds KL \u2014 Lost"
  },
  {
    "id": "1CXml1kQmGKQl7i0VbQsmS1ojGE-ETwfN",
    "from": "07/18/2026 - Impromptu Zoom Meeting",
    "to": "07/18/2026 - Impromptu Zoom Meeting (Tyron Giuliani) \u2014 Follow Up"
  },
  {
    "id": "1QRuOSGtVJfCI0b4EwniYCd5RTqAP1at0",
    "from": "07/23/2026 - Robyn Stillwater x  Andrew Musial",
    "to": "07/23/2026 - Robyn Stillwater x  Andrew Musial \u2014 Closed"
  },
  {
    "id": "1WAFZkUhGPNnICVmvSg3LP4JxvKZOCZFL",
    "from": "07/30/2026 - Impromptu Zoom Meeting",
    "to": "07/30/2026 - Impromptu Zoom Meeting (Francisco Adain Vega) \u2014 Closed"
  }
];

function dryRun()        { _process(false); }
function applyRenames()  { _process(true);  }

function _process(commit) {
  var ok = 0, skipped = 0, failed = 0;
  Logger.log(commit ? '=== APPLYING RENAMES ===' : '=== DRY RUN — no changes ===');
  for (var i = 0; i < RENAMES.length; i++) {
    var r = RENAMES[i];
    try {
      var file = DriveApp.getFileById(r.id);
      var now = file.getName();
      if (now === r.to) { skipped++; continue; }
      if (now !== r.from) {
        Logger.log('SKIP (title changed since manifest): ' + now);
        skipped++;
        continue;
      }
      if (commit) file.setName(r.to);
      Logger.log((commit ? 'RENAMED: ' : 'WOULD RENAME: ') + now + '  ->  ' + r.to);
      ok++;
    } catch (e) {
      Logger.log('FAILED ' + r.id + ': ' + e.message);
      failed++;
    }
  }
  Logger.log('--- ' + ok + ' processed, ' + skipped + ' skipped, ' + failed + ' failed ---');
}

function revertRenames() {
  var ok = 0, failed = 0;
  for (var i = 0; i < RENAMES.length; i++) {
    var r = RENAMES[i];
    try {
      var file = DriveApp.getFileById(r.id);
      if (file.getName() === r.to) { file.setName(r.from); ok++; }
    } catch (e) {
      Logger.log('REVERT FAILED ' + r.id + ': ' + e.message);
      failed++;
    }
  }
  Logger.log('--- reverted ' + ok + ', failed ' + failed + ' ---');
}
