/**
 * Primal Instinct — append call outcome to transcript filenames.
 *
 * Generated by src/build_rename_manifest.py. 422 files.
 *
 * HOW TO RUN
 *   1. script.google.com  →  New project
 *   2. Paste this whole file, replacing the default contents
 *   3. Run `dryRun` first. It logs every change WITHOUT touching anything.
 *   4. Read the log. If it looks right, run `applyRenames`.
 *   5. To undo, run `revertRenames`.
 *
 * You must be signed in as an account with edit rights on the transcripts
 * folder. The files are owned by info@primalinstinct.net — if you only have
 * view access, ask them to run it instead.
 *
 * Safe to re-run: files already carrying the suffix are skipped.
 */

var RENAMES = [
  {
    "id": "1LEsGa3eNjCCyVo6aHB2-aTehtex8N5LO",
    "from": "05/01/2026 - Bryant Fields & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/01/2026 - Bryant Fields & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1iCsiaF-48qqmUjpUlaDGTDjHIRWaiwmg",
    "from": "05/01/2026 - Parker Stratton x Harry Edmonds",
    "to": "05/01/2026 - Parker Stratton x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1_OzXXQiG_IYVslY_ohe-cOSiW84vPHqe",
    "from": "05/01/2026 - Shaz I.  x Farooq Bey",
    "to": "05/01/2026 - Shaz I.  x Farooq Bey \u2014 Closed"
  },
  {
    "id": "1vJLi4bqdJUO8JKWYxPpS2wy10t8zbDX3",
    "from": "05/02/2026 - Ad Morris x Harry Edmonds ",
    "to": "05/02/2026 - Ad Morris x Harry Edmonds \u2014 Lost"
  },
  {
    "id": "1RB7E9CfhtPlmT0uNX3EG5snPVgqZuS1n",
    "from": "05/02/2026 - Leonid Machitski & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/02/2026 - Leonid Machitski & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "1ZXJU5wMnOzdjYOjOLGARuaVmDTrQj4sY",
    "from": "05/02/2026 - Michael Angel & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/02/2026 - Michael Angel & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1mfSr3gqwQJY7p0X9pnTUVPFDbKgiWx--",
    "from": "05/03/2026 - Omar Maldy & Farooq Bey - Kettlebell Body Game Plan Session\r\n",
    "to": "05/03/2026 - Omar Maldy & Farooq Bey - Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1dT80YOo_Og3CUg2yINvCbkgUJo6Zeyrd",
    "from": "05/04/2026 - Andrew Freeman x Farooq Bey ",
    "to": "05/04/2026 - Andrew Freeman x Farooq Bey \u2014 Closed"
  },
  {
    "id": "1eNcvPS1Y4s12tM533BSanpnrZlS1srh4",
    "from": "05/04/2026 - Eliab Alvarez de la Campa x Harry Edmonds ",
    "to": "05/04/2026 - Eliab Alvarez de la Campa x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1_v5ThZPCgbo3UjepyKLYWymiCSLrLxUi",
    "from": "05/04/2026 - Impromptu Zoom Meeting",
    "to": "05/04/2026 - Impromptu Zoom Meeting (Hamdi Hmimy) \u2014 Lost"
  },
  {
    "id": "1l8-Mh6g737JLZwmKklRn4vKcyaBYkrMq",
    "from": "05/04/2026 - Impromptu Zoom Meeting",
    "to": "05/04/2026 - Impromptu Zoom Meeting (Kyle Loftus) \u2014 Lost"
  },
  {
    "id": "1zfAy6f04v9IH1yTeN8vOjKvFAJr-Kg8t",
    "from": "05/04/2026 - Donald Peteranna x Farooq Bey ",
    "to": "05/04/2026 - Donald Peteranna x Farooq Bey (Paul Bionaz) \u2014 Follow Up"
  },
  {
    "id": "1eBQWDj2KMAON3eBCubLvmiTdbO8BwwhM",
    "from": "05/04/2026 - Jaideep  Mistry x Farooq Bey",
    "to": "05/04/2026 - Jaideep  Mistry x Farooq Bey (Paul Hatch) \u2014 Follow Up"
  },
  {
    "id": "1Ejk2wtpybN9SGSpRtmRAk7_DSgsuWLQ2",
    "from": "05/04/2026 - Sunny Bal x Harry Edmonds ",
    "to": "05/04/2026 - Sunny Bal x Harry Edmonds \u2014 Undetermined"
  },
  {
    "id": "1dMAuqZg3OsfJqS7pD89aWzBShuXEtRo3",
    "from": "05/05/2026 - Andreas Xagoraris x Farooq Bey",
    "to": "05/05/2026 - Andreas Xagoraris x Farooq Bey \u2014 Lost"
  },
  {
    "id": "1PpQdUl5f-UIyNRyUUUoE8q-GOIHg00Ex",
    "from": "05/05/2026 - Eduardo P\u00e9rez x Farooq Bey",
    "to": "05/05/2026 - Eduardo P\u00e9rez x Farooq Bey (Fred) \u2014 Lost"
  },
  {
    "id": "1dgHujtzrlTZyVzP0cD0f7WWctdPaON55",
    "from": "05/05/2026 - Igor Reoutt & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/05/2026 - Igor Reoutt & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1Y-4rSNOMCek4z8UZ2MjLY9ddJFZ0ZhPp",
    "from": "05/05/2026 - Jason  Stentz x Harry Edmonds",
    "to": "05/05/2026 - Jason  Stentz x Harry Edmonds \u2014 Closed"
  },
  {
    "id": "1qdxZAYn_rwstM9nQiZuUReKcYNzImUnI",
    "from": "05/05/2026 - Mario Gallegos & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/05/2026 - Mario Gallegos & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "11ErgGTk1qkvZ_Aj7qrR5mZjgxNVkyF6N",
    "from": "05/06/2026 - Boris Kojic x Farooq Bey",
    "to": "05/06/2026 - Boris Kojic x Farooq Bey \u2014 Lost"
  },
  {
    "id": "15KM30zeFuCghZUeLHbFX1DFAqYwOO3iA",
    "from": "05/06/2026 - Brandon Johnson & Farooq Bey - Kettlebell Body Game Plan Session",
    "to": "05/06/2026 - Brandon Johnson & Farooq Bey - Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "17EbigKL0nEu01PkBbx52B7vSmJas433v",
    "from": "05/06/2026 - Joe Biagini & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/06/2026 - Joe Biagini & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "1WRo2H9vWZupIqTDZralEHJr8bIAHd6k1",
    "from": "05/06/2026 - Nicholas Ugo & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/06/2026 - Nicholas Ugo & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "1fQqQvXAwB_LMpDmYqjTOkKaalmeTOloK",
    "from": "05/06/2026 - Roy Norman x Farooq Bey",
    "to": "05/06/2026 - Roy Norman x Farooq Bey \u2014 Follow Up"
  },
  {
    "id": "1ycGd-HTUL6PIMsw8xADnVAzTS7h2Pwal",
    "from": "05/06/2026 - Ryan Franks x Farooq Bey",
    "to": "05/06/2026 - Ryan Franks x Farooq Bey \u2014 Lost"
  },
  {
    "id": "1_OJJShWGM59BQoUDovWmccJYYKRCgz4b",
    "from": "05/07/2026 - Impromptu Zoom Meeting",
    "to": "05/07/2026 - Impromptu Zoom Meeting (Atul Sharma) \u2014 Lost"
  },
  {
    "id": "1eCO9oZKQL4rx6Ej8U9CbcH697qwtrB87",
    "from": "05/07/2026 - Soneel Raj & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/07/2026 - Soneel Raj & Farooq Bey KFS- Kettlebell Body Game Plan Session (Engin Oytac) \u2014 Lost"
  },
  {
    "id": "1iRyG-th-PkYUtppNPggwi1dFAoHQ8UOd",
    "from": "05/07/2026 - Kevin Young & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/07/2026 - Kevin Young & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "19HbCbXiSgTW9EBQJLIM-2We6o4Uka36C",
    "from": "05/07/2026 - Larry Ferini & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/07/2026 - Larry Ferini & Harry Edmonds KFS- Kettlebell Body Game Plan Session [actually: Chris] \u2014 Closed"
  },
  {
    "id": "1lAo8aiOm7tQe4HJnAmezM7-KHPoMTGSk",
    "from": "05/07/2026 - Omar Rosado x Farooq Bey ",
    "to": "05/07/2026 - Omar Rosado x Farooq Bey \u2014 Follow Up"
  },
  {
    "id": "1AE7U4Fg4p77njlsj72JXTDYVNYLT527K",
    "from": "05/07/2026 - Robbie Slim & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/07/2026 - Robbie Slim & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "1eCO9oZKQL4rx6Ej8U9CbcH697qwtrB87",
    "from": "05/07/2026 - Soneel Raj & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/07/2026 - Soneel Raj & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1RyZd5HxjtHzySxwepNaoi1Doxm5twxlI",
    "from": "05/08/2026 - Christian Nazario x Farooq Bey ",
    "to": "05/08/2026 - Christian Nazario x Farooq Bey \u2014 Follow Up"
  },
  {
    "id": "13sXDTFqCpA7MKofVMhAEaVmjeM5KY-QF",
    "from": "05/08/2026 - Clive Abrahams & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/08/2026 - Clive Abrahams & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1nCCpNQjmNqRFlPUmfaNS80tP17CkuVmk",
    "from": "05/08/2026 - Fredilito Abejon & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/08/2026 - Fredilito Abejon & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "1huNHCU2JkZXZvgzYNQgqa8vLFyEcHOFe",
    "from": "05/08/2026 - Kamal Mohammed & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/08/2026 - Kamal Mohammed & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1VHFGBIHVpHmlwmDV_ONAjmWwUNosTMal",
    "from": "05/08/2026 - Tony & Farooq Bey - Kettlebell Body Game Plan Session",
    "to": "05/08/2026 - Tony & Farooq Bey - Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "1RoGS1bfR1e8RPRRKK6R-R05QVoRHnYHx",
    "from": "05/08/2026 - Varun Shankar & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/08/2026 - Varun Shankar & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1Ox2krUR3PGfEZbG3kKckIDnB3NM3EOuZ",
    "from": "05/09/2026 - Brian Begin x Harry Edmonds ",
    "to": "05/09/2026 - Brian Begin x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1-ewXFutxiVfcXmuWsDRQ58s2jVJ-rIu7",
    "from": "05/09/2026 - Chibuzor Gideon x Harry Edmonds ",
    "to": "05/09/2026 - Chibuzor Gideon x Harry Edmonds (Brian Muthami) \u2014 Closed"
  },
  {
    "id": "1jKmpmBfdJfMHHjbI05pnfLdZQ9sIbIG9",
    "from": "05/09/2026 - Luis Jauregui x Farooq Bey ",
    "to": "05/09/2026 - Luis Jauregui x Farooq Bey (Cole Carson) \u2014 Undetermined"
  },
  {
    "id": "1NFu4o5G7Seb91eeXop_wFQugdCp93j7d",
    "from": "05/09/2026 - Gerardo Alvarez & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/09/2026 - Gerardo Alvarez & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "1Wj4f8gnSK5hkCcg2NXYKcg9NNEf0ySQ2",
    "from": "05/09/2026 - Kamal Mohammed & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/09/2026 - Kamal Mohammed & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "11ysmLtNS0C8eVgQ0VMOuYV7SZsO47fUT",
    "from": "05/09/2026 - Ray Magana & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/09/2026 - Ray Magana & Farooq Bey KFS- Kettlebell Body Game Plan Session [actually: Ramon Magana] \u2014 Lost"
  },
  {
    "id": "1eTiP2SjV6YGnk29vUEn-XH0v5mqB4y_e",
    "from": "05/09/2026 - Yousof El Shamashergy x Harry Edmonds ",
    "to": "05/09/2026 - Yousof El Shamashergy x Harry Edmonds (Stephanie Lee) \u2014 Closed"
  },
  {
    "id": "1h3c04K9csxOZdZkpnu54XVpzIc5Vwjvu",
    "from": "05/10/2026 - Will Ashby x Farooq Bey KFS",
    "to": "05/10/2026 - Will Ashby x Farooq Bey KFS \u2014 Lost"
  },
  {
    "id": "1LCCpSvQur6kSICOPWHp5f6pC1p8Mcptl",
    "from": "05/11/2026 - Brady Falks x Farooq Bey ",
    "to": "05/11/2026 - Brady Falks x Farooq Bey \u2014 Closed"
  },
  {
    "id": "1q5H7mE2WKxAqqPceR8WjGFJuJQk10Wdn",
    "from": "05/11/2026 - Colin Kobza x Harry Edmonds ",
    "to": "05/11/2026 - Colin Kobza x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1r8NcFtOzG3ikXbfgGvG5ICc6Jqx6Wuxf",
    "from": "05/11/2026 - Frederic Kunz & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/11/2026 - Frederic Kunz & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "1UFA8C01br_-N3MOeaoBjkU3DXkOKdbMg",
    "from": "05/11/2026 - John White & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/11/2026 - John White & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "12uBOXIPMPB4cyBAXn1dgKd5VxWLN3SLS",
    "from": "05/11/2026 - Rafeal Sanchez x Farooq Bey ",
    "to": "05/11/2026 - Rafeal Sanchez x Farooq Bey [actually: Rafael S\u00e1nchez Carmona] \u2014 Closed"
  },
  {
    "id": "1NRW1r1qffGhaqFVuudeFwXNQN-arRRdn",
    "from": "05/11/2026 - Shawn Panjwani x Farooq Bey ",
    "to": "05/11/2026 - Shawn Panjwani x Farooq Bey (Steven Silbert) \u2014 Follow Up"
  },
  {
    "id": "1x36n7Q9FpMYqmMoKom8L_DUHruFtEipV",
    "from": "05/12/2026 - Greg Fontenot & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/12/2026 - Greg Fontenot & Farooq Bey KFS- Kettlebell Body Game Plan Session (Abraham) \u2014 Follow Up"
  },
  {
    "id": "16H66ip4IiRlrdZALkfryS4kv0PH2BQXZ",
    "from": "05/12/2026 - Bryan Langsdale x Harry Edmonds ",
    "to": "05/12/2026 - Bryan Langsdale x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1PrnnTMGQf-T9xRvQS8gGVVvnOWQFT1cr",
    "from": "05/12/2026 - Steven Silbert x Farooq Bey ",
    "to": "05/12/2026 - Steven Silbert x Farooq Bey (Cole Carson) \u2014 Follow Up"
  },
  {
    "id": "1mw62ozXVR80kuWWv8RauzDjBJS4IcKF_",
    "from": "05/12/2026 - Jacob Gaines & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/12/2026 - Jacob Gaines & Farooq Bey KFS- Kettlebell Body Game Plan Session (Dylan) \u2014 Follow Up"
  },
  {
    "id": "1YeiWhGUAEI0wP29-RWhYKw3egqRlbYo3",
    "from": "05/12/2026 - Grant Childress x Farooq Bey ",
    "to": "05/12/2026 - Grant Childress x Farooq Bey \u2014 Closed"
  },
  {
    "id": "1mw62ozXVR80kuWWv8RauzDjBJS4IcKF_",
    "from": "05/12/2026 - Jacob Gaines & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/12/2026 - Jacob Gaines & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "1UuneECUuAsNnT15JxZhItWkszpZlFHw1",
    "from": "05/12/2026 - Rob End & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/12/2026 - Rob End & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1K3i-g3AneizmiQGGNtdH-ZbxQkv6k8vS",
    "from": "05/13/2026 - Ethan John & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/13/2026 - Ethan John & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Undetermined"
  },
  {
    "id": "1fyLSdh-l_AVeS5fvmGg7TDEVeNJ3_D79",
    "from": "05/13/2026 - Jorge Suira x Farooq Bey ",
    "to": "05/13/2026 - Jorge Suira x Farooq Bey \u2014 Lost"
  },
  {
    "id": "1Xb36Wld3MAnSEYANyNFWLgoyKSw3UqAJ",
    "from": "05/13/2026 - Jorge Vargas x Farooq Bey ",
    "to": "05/13/2026 - Jorge Vargas x Farooq Bey \u2014 Follow Up"
  },
  {
    "id": "1_PAuGtOGNhwulTqFGFedWHXktdSRNP_H",
    "from": "05/13/2026 - Marc Moub & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/13/2026 - Marc Moub & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "12Ftxah9Ze4-cHPsGPVrqirkxRpmBst4S",
    "from": "05/13/2026 - Mao Sal & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/13/2026 - Mao Sal & Harry Edmonds KFS- Kettlebell Body Game Plan Session [actually: Moath Abdullah ALOBEID] \u2014 Follow Up"
  },
  {
    "id": "1ZlupfkXYFbOWTNDuzgPvRXzF1Ot_9UHY",
    "from": "05/14/2026 - Vladtest Koc x Harry Edmonds",
    "to": "05/14/2026 - Vladtest Koc x Harry Edmonds (Chance Lusk) \u2014 Follow Up"
  },
  {
    "id": "1ZEYwsvhCTpsg1hPVB0wXCPZSQrjMjuj9",
    "from": "05/14/2026 - Danny Es & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/14/2026 - Danny Es & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1ofBdakjFIUh6wtyR7p2tV6-U3AMZgp5b",
    "from": "05/14/2026 - David Williamson x Harry Edmonds ",
    "to": "05/14/2026 - David Williamson x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "13crBdMc9dTctB_1btbGlnRwAGQXozWxI",
    "from": "05/14/2026 - Zayn Malik x Harry Edmonds",
    "to": "05/14/2026 - Zayn Malik x Harry Edmonds (Kandarp) \u2014 Lost"
  },
  {
    "id": "1M4OAXfbcK4jxSQedqqhjRgUcZjOadwn8",
    "from": "05/14/2026 - Mike Sicoli & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/14/2026 - Mike Sicoli & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "1gV_WClQPp-ozQukgLlhmakw9gLbiOL3e",
    "from": "05/14/2026 - Farooq Bey / Nick hartas KFS- Meeting with Farooq",
    "to": "05/14/2026 - Farooq Bey / Nick hartas KFS- Meeting with Farooq \u2014 Follow Up"
  },
  {
    "id": "15d6JKV-vtMLRTzFy1m6Tlyu0piad4ReE",
    "from": "05/14/2026 - Prem Patel & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/14/2026 - Prem Patel & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "1H2rnT1PMyGVGzAtNlz_g84tRnyAcCkov",
    "from": "05/14/2026 - Tristian Clunis & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/14/2026 - Tristian Clunis & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1TwvcMBjmubtCSyVl2_kDoRXKgWdCcwPC",
    "from": "05/15/2026 - Aman Virji x Harry Edmonds",
    "to": "05/15/2026 - Aman Virji x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1rBI-Lde9QSlmPzFJRS84D_o3kZFU66CE",
    "from": "05/15/2026 - Brad Custis x Farooq Bey ",
    "to": "05/15/2026 - Brad Custis x Farooq Bey \u2014 Lost"
  },
  {
    "id": "1obSP70kktmQApkfFvdmxHRnXqV7N-nmZ",
    "from": "05/15/2026 - David Fouche & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/15/2026 - David Fouche & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "17t5-sSDSLYbLKy5QFe_HZMqaBSNPDz9x",
    "from": "05/15/2026 - Robert Castillo & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/15/2026 - Robert Castillo & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1LrZLfzZcTbUNs7ltt7bM1g9498TTNfxD",
    "from": "05/16/2026 - Antonio Gatlin & Farooq Bey KFS- Kettlebell Body Game Plan Session",
    "to": "05/16/2026 - Antonio Gatlin & Farooq Bey KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "1rYqjWn__JPgt9_roeLu50EMXZWh_zDmN",
    "from": "05/16/2026 - Cy Cox x Harry Edmonds ",
    "to": "05/16/2026 - Cy Cox x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "12zOPetLsa_ICa7QkDVMkPsrbw-hLak5y",
    "from": "05/16/2026 - Kurt Wollenhaupt x Harry Edmonds ",
    "to": "05/16/2026 - Kurt Wollenhaupt x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "19JG2M1Gmn0J0S8coEXWJRtrTqvv47Vyx",
    "from": "05/16/2026 - Luis Ortiz & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/16/2026 - Luis Ortiz & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Closed"
  },
  {
    "id": "1TahdBmm-iO568hb7j9wsA1vvMVvRA-Jw",
    "from": "05/16/2026 - Mustafa Jibawi & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/16/2026 - Mustafa Jibawi & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1oiiZfzATINdWXh1Afmc7kVXfHS_7uRTb",
    "from": "05/18/2026 - Andrew Gallegos x Harry Edmonds KFS ",
    "to": "05/18/2026 - Andrew Gallegos x Harry Edmonds KFS \u2014 Closed"
  },
  {
    "id": "1GoD9jabkBtrU8doVlgKoG10v1BXUyLCA",
    "from": "05/18/2026 - Eran Avshalom Ovsiovich & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/18/2026 - Eran Avshalom Ovsiovich & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1kDS9D9fEpLBig8cjkzN08-TW8Ui1-ccs",
    "from": "05/18/2026 - Galal Beshir & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/18/2026 - Galal Beshir & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Undetermined"
  },
  {
    "id": "1VNNQh012PCFH94k150W-BKOD4bqZZyBz",
    "from": "05/18/2026 - Mike Bennett x Harry Edmonds KL",
    "to": "05/18/2026 - Mike Bennett x Harry Edmonds KL \u2014 Lost"
  },
  {
    "id": "1A6u3iful8kFcBBkJyhWhR-Uue6h170xO",
    "from": "05/18/2026 - Peter Louis x Harry Edmonds",
    "to": "05/18/2026 - Peter Louis x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1tb92fiN6pYyCQNQ-C1n38gwq5AGVg4SN",
    "from": "05/19/2026 - Erenik Yzeiraj x Harry Edmonds KFS",
    "to": "05/19/2026 - Erenik Yzeiraj x Harry Edmonds KFS \u2014 Follow Up"
  },
  {
    "id": "19dSoa6I7yv1GffNgEzlOtaxsgxkr9z6s",
    "from": "05/19/2026 - Jack Heekin x Harry Edmonds",
    "to": "05/19/2026 - Jack Heekin x Harry Edmonds \u2014 Undetermined"
  },
  {
    "id": "19zbqg2M0u-PnjR9II4CncP2YnIy98sDt",
    "from": "05/19/2026 - Mike Terpin x Harry Edmonds KFS",
    "to": "05/19/2026 - Mike Terpin x Harry Edmonds KFS \u2014 Undetermined"
  },
  {
    "id": "1QUC532SZv42FFcqFTko4yo8ETQ3qzd5p",
    "from": "05/20/2026 - Fabrice Schwartz & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/20/2026 - Fabrice Schwartz & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "1ubTs-wpFPabNGWlRFZR3Syz_AWca5jRn",
    "from": "05/20/2026 - Mitchel Po x Harry Edmonds ",
    "to": "05/20/2026 - Mitchel Po x Harry Edmonds (Frederick Eisler) \u2014 Follow Up"
  },
  {
    "id": "1PVlEBw-HzWyzuTJkdg6BScb4Gosri2Ke",
    "from": "05/20/2026 - Julie Lucas & Harry Edmonds KFS- Kettlebell Body Game Plan Session",
    "to": "05/20/2026 - Julie Lucas & Harry Edmonds KFS- Kettlebell Body Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1yV0mA5AGjQxXAon7o1amx_fqxO6zhktZ",
    "from": "05/20/2026 - Shane Goodell x Harry Edmonds KFS ",
    "to": "05/20/2026 - Shane Goodell x Harry Edmonds KFS \u2014 Follow Up"
  },
  {
    "id": "1Wn0td9AikS7tVX4roH0_bOIfcLwCqfxX",
    "from": "05/20/2026 - Tayler Ireland x Harry Edmonds KFS ",
    "to": "05/20/2026 - Tayler Ireland x Harry Edmonds KFS \u2014 Lost"
  },
  {
    "id": "18DkM6SDoQG01sSRsn0hdLEHO3QUZ5SFH",
    "from": "05/21/2026 - Tony Joseph x Harry Edmonds KL- Kettlebell Body Game Plan Session",
    "to": "05/21/2026 - Tony Joseph x Harry Edmonds KL- Kettlebell Body Game Plan Session \u2014 Lost"
  },
  {
    "id": "19i9dZWtnXbj9B5olI9xkuDe8uJpnTgyP",
    "from": "05/22/2026 - Parth Shukla x Harry Edmonds KFS ",
    "to": "05/22/2026 - Parth Shukla x Harry Edmonds KFS \u2014 Closed"
  },
  {
    "id": "1vQuOVL20RwsSjXShppG3fgauE8tP-vo6",
    "from": "05/22/2026 - Ross Surratt x Harry Edmonds ",
    "to": "05/22/2026 - Ross Surratt x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1Jkco9WCmmtSsu_9M7P1H3l0QzIJFF4gC",
    "from": "05/22/2026 - Sancheet Bagtharia x Harry Edmonds KFS ",
    "to": "05/22/2026 - Sancheet Bagtharia x Harry Edmonds KFS \u2014 Follow Up"
  },
  {
    "id": "1REKjWKZfos-7CI5xF1WtIxtl3d9MkZWR",
    "from": "05/25/2026 - Andrew MusialSpotkanie Zoom 's",
    "to": "05/25/2026 - Andrew MusialSpotkanie Zoom 's (Andy) \u2014 Follow Up"
  },
  {
    "id": "1NkCTsiRAwdD2Vk8vS0bqaxmjvR2Y4i1T",
    "from": "05/25/2026 - Andrew MusialSpotkanie Zoom 's",
    "to": "05/25/2026 - Andrew MusialSpotkanie Zoom 's (Bruno) \u2014 Follow Up"
  },
  {
    "id": "1HH1tGl_B-UwVptkZCz-dR9Fxquzj0cT6",
    "from": "05/25/2026 - Daniel Manchulenko x Harry Edmonds KFS",
    "to": "05/25/2026 - Daniel Manchulenko x Harry Edmonds KFS \u2014 Closed"
  },
  {
    "id": "19ptuTGDUl3jElcpdN6uWL8iw3zXQHkS2",
    "from": "05/26/2026 - Carlo Alleva x Harry Edmonds KFS ",
    "to": "05/26/2026 - Carlo Alleva x Harry Edmonds KFS \u2014 Lost"
  },
  {
    "id": "1a2HJLbhBai7m6etEXhAR7YMuNG6tsDQk",
    "from": "05/26/2026 - David Anjomani x Harry Edmonds ",
    "to": "05/26/2026 - David Anjomani x Harry Edmonds \u2014 Lost"
  },
  {
    "id": "1Se_WQyMMiVRcDBkAspzSLkuO7BYqheKV",
    "from": "05/26/2026 - Dexter  Stewart  x Harry Edmonds",
    "to": "05/26/2026 - Dexter  Stewart  x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1NoaK2RDLDv1dmnKExZqKjSbxlhwCNBEI",
    "from": "05/26/2026 - John French x Harry Edmonds",
    "to": "05/26/2026 - John French x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1oito3gierdPxjuOS4zIyNxCy8fUVZ8Ik",
    "from": "05/26/2026 - Jorge Fern\u00e1ndez  x Andrew Musial ",
    "to": "05/26/2026 - Jorge Fern\u00e1ndez  x Andrew Musial \u2014 Lost"
  },
  {
    "id": "1SZS6kWRGBPJiqhP6RIzZEpfse3UIpN45",
    "from": "05/26/2026 - Marian G. Samson x Andrew Musial ",
    "to": "05/26/2026 - Marian G. Samson x Andrew Musial \u2014 Undetermined"
  },
  {
    "id": "1wPWGpWqQRLurmaNbwRHgiIILjcQglQMJ",
    "from": "05/27/2026 - Brooks Van Horn x Harry Edmonds KFS",
    "to": "05/27/2026 - Brooks Van Horn x Harry Edmonds KFS \u2014 Lost"
  },
  {
    "id": "1IEoPsb19lWTFJg7bpD9-ac8CEtc_fSKt",
    "from": "05/27/2026 - Cosmin Boldeanu x Harry Edmonds",
    "to": "05/27/2026 - Cosmin Boldeanu x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1LlyhfDuHb7v5fo5gebUlwQwPTIlB7-GY",
    "from": "05/27/2026 - David Wingfield x Harry Edmonds",
    "to": "05/27/2026 - David Wingfield x Harry Edmonds \u2014 Closed"
  },
  {
    "id": "16PqObGFlqpS0RZ-sO7t6FKZOLt82k29v",
    "from": "05/27/2026 - IMRAN RAFI x Harry Edmonds",
    "to": "05/27/2026 - IMRAN RAFI x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1eywnuqv8O5Z9EbyjgNaZ83JdxGJ_TxX4",
    "from": "05/27/2026 - Jared Lyons x Andrew Musial KL",
    "to": "05/27/2026 - Jared Lyons x Andrew Musial KL \u2014 Follow Up"
  },
  {
    "id": "1AOMQqmhdWJfwVsUy8rGTaR6SngFnaYPR",
    "from": "05/27/2026 - Impromptu Zoom Meeting",
    "to": "05/27/2026 - Impromptu Zoom Meeting (Marian G. Samson) \u2014 Follow Up"
  },
  {
    "id": "1PaWnBzTpmXrI__yjVIgxnzJXSx3yS6Va",
    "from": "05/27/2026 - Ram Bala x Harry Edmonds KL",
    "to": "05/27/2026 - Ram Bala x Harry Edmonds KL \u2014 Follow Up"
  },
  {
    "id": "1fUNu3mkVCN1spePmxn6BRoE4jEg1GtYC",
    "from": "05/28/2026 - Alex Rueter x Andrew Musial",
    "to": "05/28/2026 - Alex Rueter x Andrew Musial \u2014 Lost"
  },
  {
    "id": "1E9bfSAbxskRVArSLj--S_DAAD89JjQUN",
    "from": "05/28/2026 - Carlos Lopez x Harry Edmonds",
    "to": "05/28/2026 - Carlos Lopez x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1QyzJDL88sMKoZbL27TIUrS5IjIGZpti2",
    "from": "05/28/2026 - G\u00f6kmen Toroslu x Harry Edmonds ",
    "to": "05/28/2026 - G\u00f6kmen Toroslu x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1bzHbw5hCQ4BrSkQrd9GMe7Vn60g7ZP5t",
    "from": "05/28/2026 - Jo\u00e3o Dantas x Andrew Musial ",
    "to": "05/28/2026 - Jo\u00e3o Dantas x Andrew Musial \u2014 Follow Up"
  },
  {
    "id": "1t6nu0LpW2OI6VAw6WUdMEbLk3si7SwsL",
    "from": "05/28/2026 - Ken Baracaldo x Harry Edmonds",
    "to": "05/28/2026 - Ken Baracaldo x Harry Edmonds \u2014 Lost"
  },
  {
    "id": "1qUv157qaDbv1ITfEgWMunneSHrBXkWud",
    "from": "05/28/2026 - Rafal Sowa x Harry Edmonds KL",
    "to": "05/28/2026 - Rafal Sowa x Harry Edmonds KL \u2014 Follow Up"
  },
  {
    "id": "1R76UINKG1_lO59WCCPUh_iVHFzQkbSlN",
    "from": "05/28/2026 - Sharmeena Syed x Harry Edmonds KFS",
    "to": "05/28/2026 - Sharmeena Syed x Harry Edmonds KFS \u2014 Follow Up"
  },
  {
    "id": "1u5W6ohz-_sUJIBhAxBF5C1mDZZWClayk",
    "from": "05/29/2026 - Impromptu Zoom Meeting",
    "to": "05/29/2026 - Impromptu Zoom Meeting (Jared Lyons) \u2014 Lost"
  },
  {
    "id": "15LAUVIP1Pi7FqHdLzeRTt-Or7nPxcVJa",
    "from": "05/29/2026 - Eric Bergman x Andrew Musial ",
    "to": "05/29/2026 - Eric Bergman x Andrew Musial (Kurt Kelsey) \u2014 Lost"
  },
  {
    "id": "1xmmg3Emza9vx2H7jorP1d96-nz0LkH3e",
    "from": "05/29/2026 - Tristan Chalmers x Ben Byrne ",
    "to": "05/29/2026 - Tristan Chalmers x Ben Byrne \u2014 Follow Up"
  },
  {
    "id": "17nUL_IIbvbQT1s9CvFJ0des8PbdV6HDv",
    "from": "05/29/2026 - Vibhor Mishra x Ben Byrne ",
    "to": "05/29/2026 - Vibhor Mishra x Ben Byrne \u2014 Follow Up"
  },
  {
    "id": "1LbtfO0VGN1KFRZJlyJrdlQ7epdwXa6xN",
    "from": "05/30/2026 - Jacques Gerome x Andrew Musial KL",
    "to": "05/30/2026 - Jacques Gerome x Andrew Musial KL \u2014 Follow Up"
  },
  {
    "id": "1-jQxa0p5WlbZKpHFUN08UNzhzFThuEUn",
    "from": "05/30/2026 - Sean Stover x Ben Byrne KL",
    "to": "05/30/2026 - Sean Stover x Ben Byrne KL \u2014 Lost"
  },
  {
    "id": "1oz2CzaBIvhvDEAB1ywcZcWb-IHA79lvR",
    "from": "05/30/2026 - Wil Saravia x Andrew Musial KL",
    "to": "05/30/2026 - Wil Saravia x Andrew Musial KL \u2014 Follow Up"
  },
  {
    "id": "1oMdYMu5ZACK-SmGESTt7-RkRt_io6jX3",
    "from": "05/31/2026 - Hiten Patel x Andrew Musial ",
    "to": "05/31/2026 - Hiten Patel x Andrew Musial \u2014 Follow Up"
  },
  {
    "id": "1fE_a9FoT_MbLj2ZCaW3jglY7SG0Wdwpz",
    "from": "06/01/2026 - Dr Doug Stithem x Ben Byrne KL",
    "to": "06/01/2026 - Dr Doug Stithem x Ben Byrne KL \u2014 Lost"
  },
  {
    "id": "1nzB2mSYGoBdn5JpikgdVTvOCgyfa9kAj",
    "from": "06/01/2026 - James Hiza x Andrew Musial ",
    "to": "06/01/2026 - James Hiza x Andrew Musial \u2014 Closed"
  },
  {
    "id": "1t25mH_qixdesGc_NfFEpZvhm_smSDiLO",
    "from": "06/01/2026 - Cole Crossland x Ben Byrne ",
    "to": "06/01/2026 - Cole Crossland x Ben Byrne (Sascha) \u2014 Lost"
  },
  {
    "id": "1esA6ekRHPJ7ZWuMEApnAvbBWRQCzCMbv",
    "from": "06/01/2026 - Wil Saravia x Andrew Musial KL",
    "to": "06/01/2026 - Wil Saravia x Andrew Musial KL \u2014 Lost"
  },
  {
    "id": "1Ni2Xu1XLWwMo2lB1kp1AMQO2PIlcwD03",
    "from": "06/02/2026 - Akaki Kvitsiani x Ben Byrne KL",
    "to": "06/02/2026 - Akaki Kvitsiani x Ben Byrne KL \u2014 Follow Up"
  },
  {
    "id": "1v62zZynIkY2YgsVM1RQdJFSDWw_KD4H1",
    "from": "06/02/2026 - Aric Chang x Ben Byrne KL",
    "to": "06/02/2026 - Aric Chang x Ben Byrne KL \u2014 Follow Up"
  },
  {
    "id": "1sKQBizUkWMNLdTuDF5Gtjwriyx47k47j",
    "from": "06/02/2026 - Impromptu Zoom Meeting",
    "to": "06/02/2026 - Impromptu Zoom Meeting (Marian Samson) \u2014 Follow Up"
  },
  {
    "id": "1AJy_pfJZWNWJHuwLdUb929g3VLUjKwxX",
    "from": "06/02/2026 - Pat Klaver x Ben Byrne KFS",
    "to": "06/02/2026 - Pat Klaver x Ben Byrne KFS \u2014 Follow Up"
  },
  {
    "id": "13ZEbHswwEMnMZGJKPM861uEWr7khoslR",
    "from": "06/03/2026 - Fletcher Koder x Andrew Musial KFS",
    "to": "06/03/2026 - Fletcher Koder x Andrew Musial KFS \u2014 Follow Up"
  },
  {
    "id": "1j5ejY82FbsigNrwEWdag6QGA8owENJec",
    "from": "06/03/2026 - Marian Samson x Andrew Musial",
    "to": "06/03/2026 - Marian Samson x Andrew Musial \u2014 Follow Up"
  },
  {
    "id": "1mn1b_kL5em27JiwaxGMqb0AwHhrA5TlC",
    "from": "06/03/2026 - Sasa Svalina x Andrew - Game Plan Session",
    "to": "06/03/2026 - Sasa Svalina x Andrew - Game Plan Session \u2014 Follow Up"
  },
  {
    "id": "1nabiqDPWdFYcF2rb8DWle5smr-7gU_Dh",
    "from": "06/03/2026 - Impromptu Zoom Meeting",
    "to": "06/03/2026 - Impromptu Zoom Meeting (Sasa Svalina) \u2014 Closed"
  },
  {
    "id": "1FPqJBKs5zGkjPRQjOwMewS5F3LGuG-bE",
    "from": "06/03/2026 - Tim Wigg x Ben Byrne KL",
    "to": "06/03/2026 - Tim Wigg x Ben Byrne KL \u2014 Follow Up"
  },
  {
    "id": "1m8H0ICXCiHBSZzY7V5-pan2W81z4Mut0",
    "from": "06/04/2026 - Cole Crossland x Ben Byrne KFS ",
    "to": "06/04/2026 - Cole Crossland x Ben Byrne KFS \u2014 Lost"
  },
  {
    "id": "17lfMzHRG0bjR9w62TkeV_pgToXwbLI0Y",
    "from": "06/04/2026 - Thomas Proctor x Ben Byrne KFS",
    "to": "06/04/2026 - Thomas Proctor x Ben Byrne KFS \u2014 Closed"
  },
  {
    "id": "1AJ-E4PhqIpNhLoncTScjcc8BauISGXrQ",
    "from": "06/04/2026 - Usman Khan x Ben Byrne KFS ",
    "to": "06/04/2026 - Usman Khan x Ben Byrne KFS \u2014 Follow Up"
  },
  {
    "id": "1N9Uvoul8V4F5scXri8WUfz1rmL9hbp_u",
    "from": "06/05/2026 - Cole Farry x Ben Byrne KFS",
    "to": "06/05/2026 - Cole Farry x Ben Byrne KFS \u2014 Lost"
  },
  {
    "id": "1u4ErqAeXWGl8J41Jz26t6sVRhfrcra_r",
    "from": "06/05/2026 - Ruben Acosta x Ben Byrne KFS ",
    "to": "06/05/2026 - Ruben Acosta x Ben Byrne KFS \u2014 Lost"
  },
  {
    "id": "1ky_UPdB3dz9RKGkUdy-l9ALZtEGqvQgd",
    "from": "06/05/2026 - Timur Malik x Ben Byrne KL",
    "to": "06/05/2026 - Timur Malik x Ben Byrne KL \u2014 Lost"
  },
  {
    "id": "1N0rgiur55WxTf3lbu1lSiNyzQlPtNA6x",
    "from": "06/06/2026 - Billy Collazo x Andrew Musial KFS ",
    "to": "06/06/2026 - Billy Collazo x Andrew Musial KFS \u2014 Follow Up"
  },
  {
    "id": "1tvhSfIX0Ek1WLX4330TAFC3r1jeJ2_UF",
    "from": "06/06/2026 - Dan Sigman x Ben Byrne KL",
    "to": "06/06/2026 - Dan Sigman x Ben Byrne KL \u2014 Follow Up"
  },
  {
    "id": "1sJmYDJwkIICwVdMK4Fp6mKDd-5Cr4Ilh",
    "from": "06/06/2026 - Gautam Bhatia x Andrew Musial ",
    "to": "06/06/2026 - Gautam Bhatia x Andrew Musial \u2014 Closed"
  },
  {
    "id": "1QpOkkOkpCkJcZSFh8qW9DE9kpOUO7G4a",
    "from": "06/06/2026 - Jay Bremner x Ben Byrne ",
    "to": "06/06/2026 - Jay Bremner x Ben Byrne \u2014 Lost"
  },
  {
    "id": "1cBqDK_Hb5tWSe45fn_2AI69Fzjy-AFwN",
    "from": "06/06/2026 - Vishal Patel x Andrew Musial ",
    "to": "06/06/2026 - Vishal Patel x Andrew Musial \u2014 Lost"
  },
  {
    "id": "1kFOPzcOQlz5FBUm27gQrd6b16meH8u7g",
    "from": "06/07/2026 - Emerson Mendez x Andrew Musial KFS ",
    "to": "06/07/2026 - Emerson Mendez x Andrew Musial KFS \u2014 Lost"
  },
  {
    "id": "1M_mxweNy59_nucb3WLF7O0uJRYL-939q",
    "from": "06/07/2026 - Frank Abt x Ben Byrne ",
    "to": "06/07/2026 - Frank Abt x Ben Byrne \u2014 Closed"
  },
  {
    "id": "1kK3uAyMRcsVAyx-btmiplX08D1zW6ZM1",
    "from": "06/07/2026 - Jan Falesnik x Andrew Musial ",
    "to": "06/07/2026 - Jan Falesnik x Andrew Musial \u2014 Closed"
  },
  {
    "id": "1120XZxFN6dYV83-n-okv_p36RhHTlaUC",
    "from": "06/07/2026 - John Viola x Ben Byrne ",
    "to": "06/07/2026 - John Viola x Ben Byrne \u2014 Follow Up"
  },
  {
    "id": "1c5F1SNvZ3VBFeeMbx80dqile9YpCLwXY",
    "from": "06/07/2026 - Julian Malfregeot x Andrew Musial KFS",
    "to": "06/07/2026 - Julian Malfregeot x Andrew Musial KFS \u2014 Follow Up"
  },
  {
    "id": "16EQCEOBSCojFqzHFijQMu780BaKj3IEQ",
    "from": "06/07/2026 - Mike Chenard x Andrew Musial KFS",
    "to": "06/07/2026 - Mike Chenard x Andrew Musial KFS \u2014 Follow Up"
  },
  {
    "id": "1HyiqVca6HsNboy2UR6Rutd2iiVj4KGSS",
    "from": "06/08/2026 - Berish Lampert x Ben Byrne ",
    "to": "06/08/2026 - Berish Lampert x Ben Byrne \u2014 Follow Up"
  },
  {
    "id": "1-MSELYj_lYxkloIc_I0PwRDLk_m6PJTt",
    "from": "06/08/2026 - charlie vaccaro x Andrew Musial ",
    "to": "06/08/2026 - charlie vaccaro x Andrew Musial (Daniel Diaz) \u2014 Lost"
  },
  {
    "id": "1e9Gh-fGGXLD-o_6WSs3ciaAhMJFCzjgX",
    "from": "06/08/2026 - Kareem Shirazi x Andrew Musial ",
    "to": "06/08/2026 - Kareem Shirazi x Andrew Musial \u2014 Closed"
  },
  {
    "id": "1IdYeIK6fnZ4sIvSCHpSrqM8tBl3feVkg",
    "from": "06/08/2026 - Impromptu Zoom Meeting",
    "to": "06/08/2026 - Impromptu Zoom Meeting (Kareem Shirazi) \u2014 Closed"
  },
  {
    "id": "1_h9duAW6rqbBLDqNsMiEWXDCSL9Kwejk",
    "from": "06/08/2026 - Manny Nunez x Andrew Musial ",
    "to": "06/08/2026 - Manny Nunez x Andrew Musial \u2014 Follow Up"
  },
  {
    "id": "1oJnE6E3fDdqyt6Fj4cJR4plFDve6rBJP",
    "from": "06/08/2026 - Michael Freeling x Andrew Musial ",
    "to": "06/08/2026 - Michael Freeling x Andrew Musial (Pat Soldow) \u2014 Closed"
  },
  {
    "id": "1Aq6uDLojXlLDTXB5eqiywJpPcV-4cDKL",
    "from": "06/09/2026 - Ahmed Elnweshy x Andrew Musial ",
    "to": "06/09/2026 - Ahmed Elnweshy x Andrew Musial \u2014 Closed"
  },
  {
    "id": "1MqyayoUsI10YoLb9AO4ICAFk7SDzm4r4",
    "from": "06/09/2026 - Badrane Hriouch x Harry Edmonds KL",
    "to": "06/09/2026 - Badrane Hriouch x Harry Edmonds KL \u2014 Lost"
  },
  {
    "id": "1UuWmD7I6YguJ4R17Rg6VcGAzyPrhZAFU",
    "from": "06/09/2026 - Chinedu Chukelu x Harry Edmonds KL",
    "to": "06/09/2026 - Chinedu Chukelu x Harry Edmonds KL \u2014 Follow Up"
  },
  {
    "id": "1QlI3P7OXqZ6cfBQiJXIxDKQhFQpxm743",
    "from": "06/09/2026 - Jorge Alfonso x Ben Byrne ",
    "to": "06/09/2026 - Jorge Alfonso x Ben Byrne \u2014 Closed"
  },
  {
    "id": "1fPM6Ol3kKB9T3adFfCs2-cA_uEb85IbF",
    "from": "06/09/2026 - Michael Schaedle x Harry Edmonds ",
    "to": "06/09/2026 - Michael Schaedle x Harry Edmonds \u2014 Follow Up"
  },
  {
    "id": "1iOrXFrNc12QG0piqjB4lylBdZU7JKXnE",
    "from": "06/09/2026 - Ricardo Ventura x Ben Byrne ",
    "to": "06/09/2026 - Ricardo Ventura x Ben Byrne \u2014 Follow Up"
  },
  {
    "id": "1NAwq7a3euqOVLiZBVBqzZiNWPp39f1JV",
    "from": "06/10/2026 - Carlos Baston x Andrew Musial KFS ",
    "to": "06/10/2026 - Carlos Baston x Andrew Musial KFS \u2014 Lost"
  },
  {
    "id": "1uzbrtulmvzNq0zrgkAVTjADUrNtg-Yu2",
    "from": "06/10/2026 - David Elder x Ben Byrne KL",
    "to": "06/10/2026 - David Elder x Ben Byrne KL \u2014 Follow Up"
  },
  {
    "id": "1Ip6hpsVHms3VD5gg30J2_uEXd5xaNvEB",
    "from": "06/10/2026 - Joel Ortiz x Ben Byrne KFS",
    "to": "06/10/2026 - Joel Ortiz x Ben Byrne KFS \u2014 Follow Up"
  },
  {
    "id": "1SKbNB1cuQiWzhenC2YMy_obb8ZxUpE9W",
    "from": "06/10/2026 - Jonn Nolitt x Andrew Musial KFS ",
    "to": "06/10/2026 - Jonn Nolitt x Andrew Musial KFS \u2014 Closed"
  },
  {
    "id": "1ipoFwM7oceX8tqNUWSpV5l-Veh2pIoL6",
    "from": "06/11/2026 - Claudio Di Pietro x Andrew Musial KL",
    "to": "06/11/2026 - Claudio Di Pietro x Andrew Musial KL \u2014 Follow Up"
  },
  {
    "id": "15gPXX1pY5qPxtUtsZ5rljJAOnE1yylOK",
    "from": "06/11/2026 - Impromptu Zoom Meeting",
    "to": "06/11/2026 - Impromptu Zoom Meeting (David) \u2014 Follow Up"
  },
  {
    "id": "1XQwu1GV_WO62rY4lM7VlVjnmmWXevxbB",
    "from": "06/11/2026 - Impromptu Zoom Meeting",
    "to": "06/11/2026 - Impromptu Zoom Meeting (David) \u2014 Follow Up"
  },
  {
    "id": "1maf8l5KBwBs4ANhmVxaGWmDl7xu8Fmgs",
    "from": "06/11/2026 - Patrick x Andrew",
    "to": "06/11/2026 - Patrick x Andrew \u2014 Closed"
  },
  {
    "id": "1jSxTrOBanpnfGwYYh-Us2MalrrMrJlct",
    "from": "06/11/2026 - Impromptu Zoom Meeting",
    "to": "06/11/2026 - Impromptu Zoom Meeting (Tamar) \u2014 Closed"
  },
  {
    "id": "1e_-DZ_LELJgKHDKvZfrmv47J9MDiDYde",
    "from": "06/11/2026 - Impromptu Zoom Meeting",
    "to": "06/11/2026 - Impromptu Zoom Meeting (Thomas Joseph) \u2014 Closed"
  },
  {
    "id": "1duN_8fUTuOqyNzJLBwKhiJM9CrsSZgEz",
    "from": "06/11/2026 - Impromptu Zoom Meeting",
    "to": "06/11/2026 - Impromptu Zoom Meeting (Vance) \u2014 Follow Up"
  },
  {
    "id": "1CORRxw2qNWXr7ffIJT8v21WnvZCEPFUb",
    "from": "06/12/2026 - Impromptu Zoom Meeting",
    "to": "06/12/2026 - Impromptu Zoom Meeting (David) \u2014 Closed"
  },
  {
    "id": "1WLdVuvyo66MW6hA_7HjREIuItTx3bp9g",
    "from": "06/12/2026 - Impromptu Zoom Meeting",
    "to": "06/12/2026 - Impromptu Zoom Meeting (Nick) \u2014 Follow Up"
  },
  {
    "id": "1eo9wTibbi6qy8Y-kaiRY4Nz2VM2cFmQ7",
    "from": "06/13/2026 - Impromptu Zoom Meeting",
    "to": "06/13/2026 - Impromptu Zoom Meeting (Matt Smith) \u2014 Follow Up"
  },
  {
    "id": "1gmgyKhf7_hT9b9jjaZoIZcayQBgEHV8u",
    "from": "06/15/2026 - Impromptu Zoom Meeting",
    "to": "06/15/2026 - Impromptu Zoom Meeting (EJ Hernandez) \u2014 Follow Up"
  },
  {
    "id": "1LkYOCUkyIWTGznvAvbMo3kdgT9xLGpi_",
    "from": "06/15/2026 - Impromptu Zoom Meeting",
    "to": "06/15/2026 - Impromptu Zoom Meeting (Jay Moreno) \u2014 Follow Up"
  },
  {
    "id": "1Mxa4IL4gAzcTE8mPnp0LDhQMM7C-auOu",
    "from": "06/15/2026 - Impromptu Zoom Meeting",
    "to": "06/15/2026 - Impromptu Zoom Meeting (Jonathan) \u2014 Follow Up"
  },
  {
    "id": "1jTdQ9O8iSv4MJ2Jf0VMtf1RcoenU-64c",
    "from": "06/16/2026 - Impromptu Zoom Meeting",
    "to": "06/16/2026 - Impromptu Zoom Meeting (Filipe) \u2014 Lost"
  },
  {
    "id": "1eUg86WZMIxl8ulPHxBZAyXpnTECHfV9r",
    "from": "06/17/2026 - Impromptu Zoom Meeting",
    "to": "06/17/2026 - Impromptu Zoom Meeting (Erim) \u2014 Lost"
  },
  {
    "id": "1Zo4UI7nq-3wji8yC8QSFZsIGnPX9M_y6",
    "from": "06/17/2026 - Impromptu Zoom Meeting",
    "to": "06/17/2026 - Impromptu Zoom Meeting (Lane) \u2014 Closed"
  },
  {
    "id": "1ZIG_hekZYd5E3pb-nuyWr4cDuQtVGbpL",
    "from": "06/17/2026 - Impromptu Zoom Meeting",
    "to": "06/17/2026 - Impromptu Zoom Meeting \u2014 Follow Up"
  },
  {
    "id": "1UC1ULViRExkwizYkF-u3B1J-rAaHKeVG",
    "from": "06/18/2026 - Impromptu Zoom Meeting",
    "to": "06/18/2026 - Impromptu Zoom Meeting (Chandra) \u2014 Follow Up"
  },
  {
    "id": "1SZvIBWfoGPKYn7-N3E4_7pJZBxXXdcbp",
    "from": "06/18/2026 - Impromptu Zoom Meeting",
    "to": "06/18/2026 - Impromptu Zoom Meeting (Sankalp Shetty) \u2014 Follow Up"
  },
  {
    "id": "1IoPa9uRMkzqBpCLdIVnBNN_CiiD8pmNH",
    "from": "06/19/2026 - Impromptu Zoom Meeting",
    "to": "06/19/2026 - Impromptu Zoom Meeting (Donny) \u2014 Lost"
  },
  {
    "id": "1Lcc3m63TcPkxfcEOPckaA8kdiWZMwE-E",
    "from": "06/19/2026 - Impromptu Zoom Meeting",
    "to": "06/19/2026 - Impromptu Zoom Meeting (Jon Boroughs) \u2014 Follow Up"
  },
  {
    "id": "17yh3_8BH7-pKCUzQkJ3zPUT7IR77B5k5",
    "from": "06/19/2026 - Impromptu Zoom Meeting",
    "to": "06/19/2026 - Impromptu Zoom Meeting (Vik Singh) \u2014 Closed"
  },
  {
    "id": "1woK8bfUC-83vnRqCifDCJRvRi_ZaqPOB",
    "from": "06/20/2026 - Johnathan and Ben - Primal Instinct",
    "to": "06/20/2026 - Johnathan and Ben - Primal Instinct [actually: Jonathan] \u2014 Lost"
  },
  {
    "id": "1yVhuV2XZiH5bjHx_6qRp7VJSg5TmYmo_",
    "from": "06/20/2026 - Impromptu Zoom Meeting",
    "to": "06/20/2026 - Impromptu Zoom Meeting (Kristian) \u2014 Closed"
  },
  {
    "id": "1K3FIyqH9osw4zDwAPJI2yKU0QLo6-jZZ",
    "from": "06/20/2026 - Impromptu Zoom Meeting",
    "to": "06/20/2026 - Impromptu Zoom Meeting (Ray) \u2014 Follow Up"
  },
  {
    "id": "1AmR0bk4X9oExUBy_OHFxbWRVZrD5Ql0y",
    "from": "06/20/2026 - Impromptu Zoom Meeting",
    "to": "06/20/2026 - Impromptu Zoom Meeting (Tommy) \u2014 Follow Up"
  },
  {
    "id": "1rJCgEwrczQWzbW-mgZ6rU_GuqvZNJ8M8",
    "from": "06/22/2026 - Impromptu Zoom Meeting",
    "to": "06/22/2026 - Impromptu Zoom Meeting (Adene) \u2014 Lost"
  },
  {
    "id": "1NkY7VC2xAzde7VdrfkIj0b0uRXKXh1yo",
    "from": "06/22/2026 - Impromptu Zoom Meeting",
    "to": "06/22/2026 - Impromptu Zoom Meeting (Amit) \u2014 Follow Up"
  },
  {
    "id": "13CTL43Uo7kL7LJcYccxwymoSqHxeEt6Y",
    "from": "06/22/2026 - Impromptu Zoom Meeting",
    "to": "06/22/2026 - Impromptu Zoom Meeting (Farid) \u2014 Follow Up"
  },
  {
    "id": "1j27NNOVuLmzmLXzfcR7dVI1reIhK8Bef",
    "from": "06/22/2026 - Impromptu Zoom Meeting",
    "to": "06/22/2026 - Impromptu Zoom Meeting (Jacob Reyf) \u2014 Closed"
  },
  {
    "id": "1e8Mn7iT-QO8BF4IGZ_JhzXvEx9MZdhLs",
    "from": "06/22/2026 - Impromptu Zoom Meeting",
    "to": "06/22/2026 - Impromptu Zoom Meeting (Jason) \u2014 Follow Up"
  },
  {
    "id": "1peVYXfmXYRoe08a6yNWg_f3fumMDytqq",
    "from": "06/22/2026 - Impromptu Zoom Meeting",
    "to": "06/22/2026 - Impromptu Zoom Meeting (Joey Shearer) \u2014 Follow Up"
  },
  {
    "id": "17S-ETgHqYBItRqDSchXl7sWmnToaKtul",
    "from": "06/23/2026 - Impromptu Zoom Meeting",
    "to": "06/23/2026 - Impromptu Zoom Meeting (Antonio Salume) \u2014 Lost"
  },
  {
    "id": "1y1XMXv81sRoTAUX4Hd5GBYI_H0mjVjvA",
    "from": "06/23/2026 - Impromptu Zoom Meeting",
    "to": "06/23/2026 - Impromptu Zoom Meeting (Peter Tseng) \u2014 Closed"
  },
  {
    "id": "1XLGApuIBztiv0XziWkyZnnx8u5GasjRz",
    "from": "06/23/2026 - Impromptu Zoom Meeting",
    "to": "06/23/2026 - Impromptu Zoom Meeting (Robert Belanger) \u2014 Lost"
  },
  {
    "id": "1FKdjJeXPTeKKuMpD-DrwA-uTjTLW5R_K",
    "from": "06/23/2026 - Impromptu Zoom Meeting",
    "to": "06/23/2026 - Impromptu Zoom Meeting (Tyler Kirkwood) \u2014 Follow Up"
  },
  {
    "id": "1jjphH1Tow5vKrim5vqPNdK47aWjn9fkz",
    "from": "06/24/2026 - Impromptu Zoom Meeting",
    "to": "06/24/2026 - Impromptu Zoom Meeting (Daniel Solano) \u2014 Lost"
  },
  {
    "id": "184METO78wxncXefe7o5NMEkY3qGFlhd9",
    "from": "06/24/2026 - Impromptu Zoom Meeting",
    "to": "06/24/2026 - Impromptu Zoom Meeting (Douglas Rosa) \u2014 Lost"
  },
  {
    "id": "1q7BpuI-0pv-y7DZLX4s203wIr6OqO8wL",
    "from": "06/24/2026 - Impromptu Zoom Meeting",
    "to": "06/24/2026 - Impromptu Zoom Meeting (Jean-Philippe Rifaat) \u2014 Lost"
  },
  {
    "id": "1VF6oxnAnyQrTGWp1uZGf7lEbanJki3WX",
    "from": "06/24/2026 - Impromptu Zoom Meeting",
    "to": "06/24/2026 - Impromptu Zoom Meeting (Qasim Khawaja) \u2014 Follow Up"
  },
  {
    "id": "1tlfBTQbV4uwYxlkcGwOMtqBa02vKRZn9",
    "from": "06/24/2026 - Impromptu Zoom Meeting",
    "to": "06/24/2026 - Impromptu Zoom Meeting (Ryan Bundy) \u2014 Follow Up"
  },
  {
    "id": "1CpGtALJPNck0FLCZgjk9qlIljsm69UCN",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Alan) \u2014 Follow Up"
  },
  {
    "id": "19ovCnxH11K289KlR4Otp9CCCFRsrLpJE",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Carlos Dominguez) \u2014 Follow Up"
  },
  {
    "id": "13iLgA3cGY3lSB8r2B0ahS4CKLyQoVrJc",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Darius Knox) \u2014 Closed"
  },
  {
    "id": "1j0LSaCy3TsPOXPhyWRYNnupdAV1sNscX",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Kerry Ernst) \u2014 Lost"
  },
  {
    "id": "1_tOoOYCSHSsozxbyaqB3HazWNfJGPg86",
    "from": "06/25/2026 - Matteo X Richard ",
    "to": "06/25/2026 - Matteo X Richard \u2014 Closed"
  },
  {
    "id": "1WSNJRG8mX9-BpVOc0kuYGmAOwe1ATjMm",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Maz) \u2014 Follow Up"
  },
  {
    "id": "1_zoaB_ZKmtkZrv-W47SQu1iGRVY9vpZ9",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Peter Nelson) \u2014 Follow Up"
  },
  {
    "id": "1f48fSQ33WjpakBuD5qucuBvySRs-YkxZ",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Suman) \u2014 Follow Up"
  },
  {
    "id": "1f5mznhTJTKt0bRHONsHz6y0HLQi7lpYU",
    "from": "06/25/2026 - Impromptu Zoom Meeting",
    "to": "06/25/2026 - Impromptu Zoom Meeting (Tyler Moye) \u2014 Closed"
  },
  {
    "id": "117WTSVshGkyf4e0VNYMd8FfQb0Lxg3ff",
    "from": "06/26/2026 - Impromptu Zoom Meeting",
    "to": "06/26/2026 - Impromptu Zoom Meeting (Shahzad Butt) \u2014 Follow Up"
  },
  {
    "id": "1RvOURa-BcixUAxZsLPHv8AdmFRekU0fb",
    "from": "06/26/2026 - Impromptu Zoom Meeting",
    "to": "06/26/2026 - Impromptu Zoom Meeting (Tyler) \u2014 Follow Up"
  },
  {
    "id": "1JOtnl-SvVG0bVAiiJXmYxC-WXWO__BlX",
    "from": "06/27/2026 - Impromptu Zoom Meeting",
    "to": "06/27/2026 - Impromptu Zoom Meeting (Ady) \u2014 Follow Up"
  },
  {
    "id": "16aubZxx9eClqBTDb98Bw0Pk2wJOaKpkb",
    "from": "06/27/2026 - Impromptu Zoom Meeting",
    "to": "06/27/2026 - Impromptu Zoom Meeting (Jacob) \u2014 Follow Up"
  },
  {
    "id": "1n672FBLaD4emmSehYT3jrAUILIn8F5qW",
    "from": "06/28/2026 - Impromptu Zoom Meeting",
    "to": "06/28/2026 - Impromptu Zoom Meeting (Caesar Lins) \u2014 Lost"
  },
  {
    "id": "1d38PAcTdur8bx61HZaP2LTEQtou8ygyk",
    "from": "06/28/2026 - Impromptu Zoom Meeting",
    "to": "06/28/2026 - Impromptu Zoom Meeting (Jared) \u2014 Closed"
  },
  {
    "id": "1_Di8ODe2OqCLXigTb09vRz7yKp30GzNR",
    "from": "06/28/2026 - Impromptu Zoom Meeting",
    "to": "06/28/2026 - Impromptu Zoom Meeting (Siddiq Farid) \u2014 Follow Up"
  },
  {
    "id": "10V86er3ny38IyHUtnvm7OIAGEsMM29Kl",
    "from": "06/28/2026 - Impromptu Zoom Meeting",
    "to": "06/28/2026 - Impromptu Zoom Meeting (Yash) \u2014 Follow Up"
  },
  {
    "id": "18a4jk_lj2nZa9SquAbTDtVxLhdWcNhcy",
    "from": "06/29/2026 - Impromptu Zoom Meeting",
    "to": "06/29/2026 - Impromptu Zoom Meeting (Dimitri Fischler) \u2014 Lost"
  },
  {
    "id": "1Ko34ltlnuS-Q-YvKiiieyHgSGcgPQMJp",
    "from": "06/29/2026 - Impromptu Zoom Meeting",
    "to": "06/29/2026 - Impromptu Zoom Meeting (Everett) \u2014 Follow Up"
  },
  {
    "id": "1XZqVutTFZLpowM-7PFviWTfYsaiGr8fA",
    "from": "06/29/2026 - Impromptu Zoom Meeting",
    "to": "06/29/2026 - Impromptu Zoom Meeting (Marc) \u2014 Follow Up"
  },
  {
    "id": "1ljeNnJbN8y9-rm9m0uHFuET27zDjPRz8",
    "from": "06/29/2026 - Impromptu Zoom Meeting",
    "to": "06/29/2026 - Impromptu Zoom Meeting (Nader) \u2014 Lost"
  },
  {
    "id": "1f5JiE_O0EIx73-qLgcNmRFLRu-4gAFzB",
    "from": "06/29/2026 - Impromptu Zoom Meeting",
    "to": "06/29/2026 - Impromptu Zoom Meeting (Nikhil Amin) \u2014 Closed"
  },
  {
    "id": "1Ssfa8OpEM-3kzAd7izZAKCMMqHmB4PHJ",
    "from": "06/29/2026 - Impromptu Zoom Meeting",
    "to": "06/29/2026 - Impromptu Zoom Meeting (Nikhil) \u2014 Follow Up"
  },
  {
    "id": "1Pu836dF6c_qDQ13ivPqTofMugFJbLQqV",
    "from": "06/29/2026 - Impromptu Zoom Meeting",
    "to": "06/29/2026 - Impromptu Zoom Meeting (Siddiq Farid) \u2014 Follow Up"
  },
  {
    "id": "1tzaYOLjJ_Kq9M6vxJTOGwVnDQuzyefgF",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Alex) \u2014 Closed"
  },
  {
    "id": "1rGUqVAxwMdBbStgjOwuVdA7nmolXEWRK",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Anthony Acosta) \u2014 Lost"
  },
  {
    "id": "1Gxs_CszMBHEejQvHrbqOjET2rL3caOne",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Basel) \u2014 Follow Up"
  },
  {
    "id": "1rZkIw4zpg0Sn_R6ZRt7iVTvBKMeYrxce",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Carl Fiorentino) \u2014 Follow Up"
  },
  {
    "id": "1jXHvTEFJIltXUibwmGEVO7XaANtG_Wip",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Giovanni Sornatale) \u2014 Follow Up"
  },
  {
    "id": "1ZaMS6HHEQws0adaC44vvwcGczY57i61k",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Hitten) \u2014 Lost"
  },
  {
    "id": "1YDuJ8QapY066a50diMvjJxiKLn4DlWVk",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Matthew) \u2014 Follow Up"
  },
  {
    "id": "1637Nkd3MoW2tjKw5_ZL-3UeS64QtVcry",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Shyam) \u2014 Lost"
  },
  {
    "id": "15Tn2swBNcC9mvblX51sw4zTJiRZHRqmC",
    "from": "06/30/2026 - Impromptu Zoom Meeting",
    "to": "06/30/2026 - Impromptu Zoom Meeting (Xaime) \u2014 Lost"
  },
  {
    "id": "1dFx1CmiHXH6g261XJuiWElaz_dLUr_wD",
    "from": "07/01/2026 - Impromptu Zoom Meeting",
    "to": "07/01/2026 - Impromptu Zoom Meeting (Martin) \u2014 Closed"
  },
  {
    "id": "189Z9g_0EWcM4O8DnIj12gHYb3WYPEzI_",
    "from": "07/01/2026 - Impromptu Zoom Meeting",
    "to": "07/01/2026 - Impromptu Zoom Meeting (Nate Slayton) \u2014 Follow Up"
  },
  {
    "id": "1Cy4VhIWy_H5jjHIkM3UAARIgI5XVdDGw",
    "from": "07/01/2026 - Impromptu Zoom Meeting",
    "to": "07/01/2026 - Impromptu Zoom Meeting (Sako) \u2014 Follow Up"
  },
  {
    "id": "1w9p0jia5BzLO-XtKaA4OKQJRmXkvRPFI",
    "from": "07/02/2026 - Impromptu Zoom Meeting",
    "to": "07/02/2026 - Impromptu Zoom Meeting (Charlie) \u2014 Closed"
  },
  {
    "id": "1pYwvC4nr7HQoA8JuFbIKBMWFvyBu_JWg",
    "from": "07/02/2026 - Impromptu Zoom Meeting",
    "to": "07/02/2026 - Impromptu Zoom Meeting (Felipe Dublanc) \u2014 Follow Up"
  },
  {
    "id": "11jjuQIlcOwJiuAhlXfm41Gd2uH5FPSJT",
    "from": "07/02/2026 - Impromptu Zoom Meeting",
    "to": "07/02/2026 - Impromptu Zoom Meeting (Irfan) \u2014 Lost"
  },
  {
    "id": "1gjdTveTcD5OMS97-9ywZ8qw39RUSdnJy",
    "from": "07/02/2026 - Impromptu Zoom Meeting",
    "to": "07/02/2026 - Impromptu Zoom Meeting (James) \u2014 Follow Up"
  },
  {
    "id": "1V96VziEDui5ya-9I51XY3E67EesfzZlb",
    "from": "07/02/2026 - Michael Mazey x Andrew Musial KFS",
    "to": "07/02/2026 - Michael Mazey x Andrew Musial KFS \u2014 Follow Up"
  },
  {
    "id": "1KJSgpMzPYH5k1SwrtMV1DTeyqH7QmaZe",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Andrew Clarke) \u2014 Follow Up"
  },
  {
    "id": "1mH5twR0W4hnOAStQh3LTyxb_u0CzYuln",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Andrew Kline) \u2014 Follow Up"
  },
  {
    "id": "15O42ddMbbh21MxJet8HZhWBDPZTKFGMz",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Andy Wall) \u2014 Follow Up"
  },
  {
    "id": "1m3rk_7Pav151XYgHG2Ianu83_83qL-1A",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Anthony Boon) \u2014 Follow Up"
  },
  {
    "id": "13xx7uzQzPX97_iY9N-4-GihvIe5i63no",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Chris) \u2014 Follow Up"
  },
  {
    "id": "1sGPvkiE1N2-nxFO55kiyGY2Br1GSrAok",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Daniel) \u2014 Follow Up"
  },
  {
    "id": "1KqnsBvHLfI8V90saguBCmSzRXpSGTevY",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Eddie) \u2014 Follow Up"
  },
  {
    "id": "1pSdH5n4pWihYNtlrUTjPYAbxdg_Ydsh3",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Jeroen Lodder) \u2014 Lost"
  },
  {
    "id": "1KGVs4c4ML8gFUIm1pKF2E9kdcxRI-yOj",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Jerry Harding) \u2014 Follow Up"
  },
  {
    "id": "1U_36GO9x37hua0VvVa8R3PO1sd5jWcEY",
    "from": "07/03/2026 - Michael Mazey x Michael Brideau KFS",
    "to": "07/03/2026 - Michael Mazey x Michael Brideau KFS \u2014 Closed"
  },
  {
    "id": "1V__JCV_jfl08Y9NpFnuNsWceXg0qKoN1",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Sam) \u2014 Follow Up"
  },
  {
    "id": "1UxBMgj-gJQy_mGo4D3eUXHcSie_O1Hg9",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Tom Eldon) \u2014 Follow Up"
  },
  {
    "id": "1lyZsLeec8wPqwmgoBEEbASIs9FIcp7vi",
    "from": "07/03/2026 - Impromptu Zoom Meeting",
    "to": "07/03/2026 - Impromptu Zoom Meeting (Tom) \u2014 Follow Up"
  },
  {
    "id": "1QuhwfPmrbbdi-I702LeGx-7bdEzYrN91",
    "from": "07/04/2026 - Impromptu Zoom Meeting",
    "to": "07/04/2026 - Impromptu Zoom Meeting (Eddie) \u2014 Follow Up"
  },
  {
    "id": "121vKH-LzIcsnwN7eL4pmlCiVuQugoAxM",
    "from": "07/04/2026 - Impromptu Zoom Meeting",
    "to": "07/04/2026 - Impromptu Zoom Meeting (Hariharan Ramanarayanan) \u2014 Follow Up"
  },
  {
    "id": "1NyxvUixgezpRySpEYrYOlSMJ3rfgn1y9",
    "from": "07/04/2026 - Impromptu Zoom Meeting",
    "to": "07/04/2026 - Impromptu Zoom Meeting (John Williamson) \u2014 Follow Up"
  },
  {
    "id": "1GQXVz4CUO1u7Qn1n3TGdICAhLusrOZ-g",
    "from": "07/04/2026 - Impromptu Zoom Meeting",
    "to": "07/04/2026 - Impromptu Zoom Meeting (Kyle) \u2014 Undetermined"
  },
  {
    "id": "1uV5AtdpFGBSE2c7EQsW7O7BGcos-p8tJ",
    "from": "07/04/2026 - Impromptu Zoom Meeting",
    "to": "07/04/2026 - Impromptu Zoom Meeting (Travis Owen) \u2014 Follow Up"
  },
  {
    "id": "1yIP0xyK-m-f0Lnv4KYS0XSnvLzAsujDg",
    "from": "07/05/2026 - Impromptu Zoom Meeting",
    "to": "07/05/2026 - Impromptu Zoom Meeting (Itai) \u2014 Follow Up"
  },
  {
    "id": "1Vc7GlAz5VCIUB0IIb-hoK6J-OpGKJfPR",
    "from": "07/05/2026 - Impromptu Zoom Meeting",
    "to": "07/05/2026 - Impromptu Zoom Meeting (John) \u2014 Follow Up"
  },
  {
    "id": "1S2h_cBL4ht9UWE3NN_7w5Vs_TLHWAJGk",
    "from": "07/05/2026 - Impromptu Zoom Meeting",
    "to": "07/05/2026 - Impromptu Zoom Meeting (Mandeep Daby) \u2014 Follow Up"
  },
  {
    "id": "1UcU98tZzYSVnsHsMGf6_Rl96wF5yuNm6",
    "from": "07/05/2026 - Impromptu Zoom Meeting",
    "to": "07/05/2026 - Impromptu Zoom Meeting (Robert Karssiens) \u2014 Follow Up"
  },
  {
    "id": "1rEocUTVuAf-9kaeRv97zaDpZI1FCzxps",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (Abdul Malik Mohammed) \u2014 Follow Up"
  },
  {
    "id": "1Ph9ddDSQN7Ur7B8VRye2kMFCUBzZXHIB",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (Brian) \u2014 Follow Up"
  },
  {
    "id": "1ZVwCF8TAkrDlzr3W89_LJ3TcLKb82Ypj",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (Daniel) \u2014 Closed"
  },
  {
    "id": "1zX7Od6WsSzGeASfXl22iwrTbndBVcv4H",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (Den Keo) \u2014 Closed"
  },
  {
    "id": "1m-ZZvlqLO9h-hu-R3jUOuumTrj-Xmmig",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (Jess) \u2014 Lost"
  },
  {
    "id": "17zm24ZiWfxh0aM0PqdcwjxDeY-Bc2Zmn",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (John Williamson) \u2014 Lost"
  },
  {
    "id": "1u6EMnlYIXlel8pVTEpjCWkmuNMlE463O",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (Nic) \u2014 Follow Up"
  },
  {
    "id": "1nt7CNF3gnROrkyntNynjIYE8y8zSdyUN",
    "from": "07/06/2026 - Impromptu Zoom Meeting",
    "to": "07/06/2026 - Impromptu Zoom Meeting (Thomas A Dixon) \u2014 Follow Up"
  },
  {
    "id": "1h-SCG-YxuYGwJmrd01l8X1jgCBdNORGy",
    "from": "07/07/2026 - Impromptu Zoom Meeting",
    "to": "07/07/2026 - Impromptu Zoom Meeting (Anthony Sosa) \u2014 Closed"
  },
  {
    "id": "1sdRoeT52xCEszBxXGxQpLhEogo1NzfSs",
    "from": "07/07/2026 - Impromptu Zoom Meeting",
    "to": "07/07/2026 - Impromptu Zoom Meeting (Frank Somma) \u2014 Follow Up"
  },
  {
    "id": "1inryx5f03dMD8QsluH0bQ-zzITV62t2F",
    "from": "07/07/2026 - Impromptu Zoom Meeting",
    "to": "07/07/2026 - Impromptu Zoom Meeting (Jake Brenner) \u2014 Closed"
  },
  {
    "id": "1IH_qVlcPCnmmfIw8OJxo_AjQPEumwZqY",
    "from": "07/07/2026 - Impromptu Zoom Meeting",
    "to": "07/07/2026 - Impromptu Zoom Meeting (Luke Charleston) \u2014 Lost"
  },
  {
    "id": "1uv-1GWy_YrozzwSwoznTvVV9CgEayhLe",
    "from": "07/07/2026 - Impromptu Zoom Meeting",
    "to": "07/07/2026 - Impromptu Zoom Meeting (Tyler Stillwater) \u2014 Closed"
  },
  {
    "id": "1VRrCOqT_fc6iqAnGfXFtd_L-l4AhUD4Z",
    "from": "07/08/2026 - Impromptu Zoom Meeting",
    "to": "07/08/2026 - Impromptu Zoom Meeting (Brandon Shpirt) \u2014 Follow Up"
  },
  {
    "id": "1sfdo9-gh78gL9nIUhNe9k19Woj1LT-D3",
    "from": "07/08/2026 - Impromptu Zoom Meeting",
    "to": "07/08/2026 - Impromptu Zoom Meeting (DJ Hayden) \u2014 Undetermined"
  },
  {
    "id": "12k2r3H4NhN2znmsMO3x_Cit5up31Omxv",
    "from": "07/08/2026 - Impromptu Zoom Meeting",
    "to": "07/08/2026 - Impromptu Zoom Meeting (Jacob) \u2014 Follow Up"
  },
  {
    "id": "17vDhyBXp293scCHt_BLl3pzgASnYabs-",
    "from": "07/08/2026 - Impromptu Zoom Meeting",
    "to": "07/08/2026 - Impromptu Zoom Meeting (Jonathan) \u2014 Lost"
  },
  {
    "id": "1CtAAQEYBm7YG8dCmAYOrChVATPDuqVac",
    "from": "07/08/2026 - Impromptu Zoom Meeting",
    "to": "07/08/2026 - Impromptu Zoom Meeting (Max) \u2014 Follow Up"
  },
  {
    "id": "1X7PloVHfxEJechIUlnKZMmAfMVSeG-ST",
    "from": "07/08/2026 - Impromptu Zoom Meeting",
    "to": "07/08/2026 - Impromptu Zoom Meeting (Nadav Roth) \u2014 Lost"
  },
  {
    "id": "1Iv7_j-ysQRPHbBxZswXlm12lvXadOQTv",
    "from": "07/09/2026 - Impromptu Zoom Meeting",
    "to": "07/09/2026 - Impromptu Zoom Meeting (Anthony) \u2014 Follow Up"
  },
  {
    "id": "1fewL708N9CuBXELUZodaz4VYU0FMKtky",
    "from": "07/09/2026 - Impromptu Zoom Meeting",
    "to": "07/09/2026 - Impromptu Zoom Meeting (Fr\u00e9d\u00e9ric IPE) \u2014 Follow Up"
  },
  {
    "id": "1l1nNV6DfQ-lerIGk5Fv6Nppz95IMzMga",
    "from": "07/09/2026 - Impromptu Zoom Meeting",
    "to": "07/09/2026 - Impromptu Zoom Meeting (Georgy S) \u2014 Follow Up"
  },
  {
    "id": "1sgV4BKOTcbbnFGU0f8vp3WoZ4uLfJEUP",
    "from": "07/09/2026 - Impromptu Zoom Meeting",
    "to": "07/09/2026 - Impromptu Zoom Meeting (Latham York) \u2014 Follow Up"
  },
  {
    "id": "1GEAw0NE9MYRfw6anDDHSGBFghhj557u4",
    "from": "07/09/2026 - Impromptu Zoom Meeting",
    "to": "07/09/2026 - Impromptu Zoom Meeting (Manish) \u2014 Follow Up"
  },
  {
    "id": "1UBS-Uv5Np9uGiXCNdZ6e1YKW0Fo9hgks",
    "from": "07/09/2026 - Impromptu Zoom Meeting",
    "to": "07/09/2026 - Impromptu Zoom Meeting (Xiao Xie) \u2014 Follow Up"
  },
  {
    "id": "1cC3RRQGEPGpv_jWmzLXPiQ2YJk5IkTY1",
    "from": "07/09/2026 - Impromptu Zoom Meeting",
    "to": "07/09/2026 - Impromptu Zoom Meeting (Yosef Resnick) \u2014 Lost"
  },
  {
    "id": "1bcf9n_h7NUgnTjz8dYwBx807rJScAklQ",
    "from": "07/10/2026 - Impromptu Zoom Meeting",
    "to": "07/10/2026 - Impromptu Zoom Meeting (Brent) \u2014 Follow Up"
  },
  {
    "id": "1SLFJHuEABsvngnYZB9gyRi0L9hnRO2rQ",
    "from": "07/10/2026 - Impromptu Zoom Meeting",
    "to": "07/10/2026 - Impromptu Zoom Meeting (Hugo) \u2014 Follow Up"
  },
  {
    "id": "11y1WMoaAa0ZgWd6wQUK1hVOBzqh-glfP",
    "from": "07/10/2026 - Impromptu Zoom Meeting",
    "to": "07/10/2026 - Impromptu Zoom Meeting (Joshua Falkner) \u2014 Lost"
  },
  {
    "id": "1JtoUADAWLx4roBrSGeusIc7B1MC7FJS1",
    "from": "07/10/2026 - Impromptu Zoom Meeting",
    "to": "07/10/2026 - Impromptu Zoom Meeting (Miguel \u00c1ngel) \u2014 Lost"
  },
  {
    "id": "1hWTo1PzfalS7AsA2eDNQRGILW6CMStEq",
    "from": "07/10/2026 - Impromptu Zoom Meeting",
    "to": "07/10/2026 - Impromptu Zoom Meeting (Sourav Kumar) \u2014 Lost"
  },
  {
    "id": "14Hb-o7f5BarsQcPSAfG95APBehNfHLMH",
    "from": "07/10/2026 - Impromptu Zoom Meeting",
    "to": "07/10/2026 - Impromptu Zoom Meeting (Woodley Vericain) \u2014 Follow Up"
  },
  {
    "id": "1C4H4C0BUWozKuPTVT-k7Pmrb9QcJVfpt",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Alex) \u2014 Follow Up"
  },
  {
    "id": "1N7UOumntJEnSGeZCbXzowL79uYPxCnr3",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Colt Campbell) \u2014 Follow Up"
  },
  {
    "id": "1C2h_5tbEo3ZrvVWCakW3VaxpIxX0CN34",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Craig) \u2014 Follow Up"
  },
  {
    "id": "1B4enNYeTi3sZGM30S5WHSvAse5amdXMi",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Damien) \u2014 Follow Up"
  },
  {
    "id": "1TeCc36oCOG72jrlv_7hac8r3RBQ3vqAQ",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Fabien COLLEC) \u2014 Follow Up"
  },
  {
    "id": "1rVvvswy15tCCRBQu8KnYX2JlglI496YT",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Jos\u00e9) \u2014 Follow Up"
  },
  {
    "id": "1BbC2s8Tw2vUlV28vgrI8JJn6W869qmcP",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Juan Aguilera) \u2014 Follow Up"
  },
  {
    "id": "1A8Y0ioL0g-CjQ48_PGIQKgtnpX_KbZjB",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Rohan) \u2014 Follow Up"
  },
  {
    "id": "1Sjo443QdAckZkQf8b8Vdn1fuHV2M8dun",
    "from": "07/11/2026 - Impromptu Zoom Meeting",
    "to": "07/11/2026 - Impromptu Zoom Meeting (Sam) \u2014 Lost"
  },
  {
    "id": "1CBNv8hR7kq2gKnz1E19SpFJjIioXwooA",
    "from": "07/12/2026 - Impromptu Zoom Meeting",
    "to": "07/12/2026 - Impromptu Zoom Meeting (Cosmi) \u2014 Follow Up"
  },
  {
    "id": "1MyJKplk140Nk-OlqDKsSWUyr1SyoK7rq",
    "from": "07/12/2026 - Impromptu Zoom Meeting",
    "to": "07/12/2026 - Impromptu Zoom Meeting (Damein Wells) \u2014 Follow Up"
  },
  {
    "id": "1U6e2CoXIZxr30m-3U6I5ii-qrkJhBRpr",
    "from": "07/12/2026 - Impromptu Zoom Meeting",
    "to": "07/12/2026 - Impromptu Zoom Meeting (Dustin Arnheim) \u2014 Follow Up"
  },
  {
    "id": "1Bn1roZc9Otaed3B0GFEWEK-C3GhHeR8s",
    "from": "07/12/2026 - Impromptu Zoom Meeting",
    "to": "07/12/2026 - Impromptu Zoom Meeting (Kathie) \u2014 Follow Up"
  },
  {
    "id": "1bpZdVJNTbLBKiWXgmimztbpxIkrjI5or",
    "from": "07/12/2026 - Impromptu Zoom Meeting",
    "to": "07/12/2026 - Impromptu Zoom Meeting (Michael L) \u2014 Follow Up"
  },
  {
    "id": "16s65F8mZeY5w_dDqtfXl1jhWe3H-345q",
    "from": "07/12/2026 - Impromptu Zoom Meeting",
    "to": "07/12/2026 - Impromptu Zoom Meeting (Samuel Mathew) \u2014 Lost"
  },
  {
    "id": "1MPxXdsBzrHK6vWczWqYOhcvVaDh4tX7s",
    "from": "07/13/2026 - Impromptu Zoom Meeting",
    "to": "07/13/2026 - Impromptu Zoom Meeting (Brandon Blair) \u2014 Lost"
  },
  {
    "id": "1BeZBvHXHcodHVqz_v9A9rjDY5ODtYXqX",
    "from": "07/13/2026 - Impromptu Zoom Meeting",
    "to": "07/13/2026 - Impromptu Zoom Meeting (Darwin) \u2014 Follow Up"
  },
  {
    "id": "1mhFg2HyMEeTt1MmxuO6PSotzwyVMYdmX",
    "from": "07/13/2026 - Impromptu Zoom Meeting",
    "to": "07/13/2026 - Impromptu Zoom Meeting (Justin Rascoe) \u2014 Lost"
  },
  {
    "id": "1qd4kJODUZRbuCQ18BpoxRHMNMXsON_3X",
    "from": "07/13/2026 - Impromptu Zoom Meeting",
    "to": "07/13/2026 - Impromptu Zoom Meeting (Ken Dunham) \u2014 Follow Up"
  },
  {
    "id": "1mt-qxTCepiIBNZ0s0Q8ac1Ylo4gdx-U3",
    "from": "07/13/2026 - Impromptu Zoom Meeting",
    "to": "07/13/2026 - Impromptu Zoom Meeting (Ken Dunham) \u2014 Closed"
  },
  {
    "id": "1mt-qxTCepiIBNZ0s0Q8ac1Ylo4gdx-U3",
    "from": "07/13/2026 - Impromptu Zoom Meeting",
    "to": "07/13/2026 - Impromptu Zoom Meeting (Saagar Patel-Francis) \u2014 Follow Up"
  },
  {
    "id": "1qNFoj1omXGF51fgib1JmxYHuW0CX44aU",
    "from": "07/13/2026 - Impromptu Zoom Meeting",
    "to": "07/13/2026 - Impromptu Zoom Meeting \u2014 Follow Up"
  },
  {
    "id": "18wH1x6FKtaOB7wziGzRi4dDry4gMS9f2",
    "from": "07/14/2026 - Impromptu Zoom Meeting",
    "to": "07/14/2026 - Impromptu Zoom Meeting (Brandon Salisbury) \u2014 Follow Up"
  },
  {
    "id": "18wH1x6FKtaOB7wziGzRi4dDry4gMS9f2",
    "from": "07/14/2026 - Impromptu Zoom Meeting",
    "to": "07/14/2026 - Impromptu Zoom Meeting (Joanna Rattan) \u2014 Undetermined"
  },
  {
    "id": "1DzXLe5Sm5KHTKBYCu1EzxoMJompLPOph",
    "from": "07/14/2026 - Impromptu Zoom Meeting",
    "to": "07/14/2026 - Impromptu Zoom Meeting (Maciej Chodorowski) \u2014 Lost"
  },
  {
    "id": "1mccIxlF8khbxGgR9LLYY1uQaolD0zH6d",
    "from": "07/14/2026 - Impromptu Zoom Meeting",
    "to": "07/14/2026 - Impromptu Zoom Meeting (Tony) \u2014 Lost"
  },
  {
    "id": "1TY5F12DugGLjvAAOgFZUJzLxxMzLDuQ9",
    "from": "07/15/2026 - Impromptu Zoom Meeting",
    "to": "07/15/2026 - Impromptu Zoom Meeting (Joanna Rattan) \u2014 Lost"
  },
  {
    "id": "15OPhdLCqAtn26dwjo6U3Sjl-cj6ZFUz8",
    "from": "07/15/2026 - Impromptu Zoom Meeting",
    "to": "07/15/2026 - Impromptu Zoom Meeting (Jonesie) \u2014 Follow Up"
  },
  {
    "id": "13DX23RA_N-VonlwHeljICNUwbL4EEYEe",
    "from": "07/15/2026 - Impromptu Zoom Meeting",
    "to": "07/15/2026 - Impromptu Zoom Meeting (Nick) \u2014 Closed"
  },
  {
    "id": "1AVuQq3ryFaduIFDL1JfK5QObDmzR2FBx",
    "from": "07/15/2026 - Impromptu Zoom Meeting",
    "to": "07/15/2026 - Impromptu Zoom Meeting (Rodrigo) \u2014 Follow Up"
  },
  {
    "id": "15OPhdLCqAtn26dwjo6U3Sjl-cj6ZFUz8",
    "from": "07/15/2026 - Impromptu Zoom Meeting",
    "to": "07/15/2026 - Impromptu Zoom Meeting (Ryan) \u2014 Follow Up"
  },
  {
    "id": "1Nf-HOgPqh7MZZFPPulqMtq2sm4Br-fQQ",
    "from": "07/15/2026 - Impromptu Zoom Meeting",
    "to": "07/15/2026 - Impromptu Zoom Meeting (Sal) \u2014 Closed"
  },
  {
    "id": "1I882P-GLWndoEzEqijbGK1Qjg8U0l6Je",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Chris Valiente) \u2014 Follow Up"
  },
  {
    "id": "1SKFwRYwnTpHdAsfIweNhgqLWBBbzG_6P",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Chris Wiley) \u2014 Closed"
  },
  {
    "id": "1i3XqlFGCfv20BBy4TDQTwd92T8gnpTCm",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (David Moyle) \u2014 Follow Up"
  },
  {
    "id": "1ir0n61mm73Glldn3dCXfnU6AMR9cfV6-",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Emmanuel Caraballo) \u2014 Follow Up"
  },
  {
    "id": "1zhFxbrCAyby9qtlf0uAv6pXPcHDErl59",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Evangelos Averkiou) \u2014 Lost"
  },
  {
    "id": "1_tD3ZPXamdXOzlQ4EEB4DqTfnORdvX0V",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Saeed) \u2014 Follow Up"
  },
  {
    "id": "1SKFwRYwnTpHdAsfIweNhgqLWBBbzG_6P",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Steve Dawson) \u2014 Closed"
  },
  {
    "id": "1vMhm5bsayv00GcQref6cRrdygnz0C2yi",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Tahseen Chisti) \u2014 Follow Up"
  },
  {
    "id": "1YvbHP-6nWTBf4KXZpAgOFc_ZkdM20_Qw",
    "from": "07/16/2026 - Impromptu Zoom Meeting",
    "to": "07/16/2026 - Impromptu Zoom Meeting (Tyron Giuliani) \u2014 Follow Up"
  },
  {
    "id": "1j8kz7sLsBzuvb3CSK0h-Q6KH48aqN61x",
    "from": "07/17/2026 - Impromptu Zoom Meeting",
    "to": "07/17/2026 - Impromptu Zoom Meeting (Alexandre Lesbats) \u2014 Follow Up"
  },
  {
    "id": "1I82KWdhMXC-219pi4fUABngbOa4AO_Yt",
    "from": "07/17/2026 - Impromptu Zoom Meeting",
    "to": "07/17/2026 - Impromptu Zoom Meeting (Ali) \u2014 Follow Up"
  },
  {
    "id": "1QxKk_DrN8OkAQAV1BsJyURvwlnz2jpXa",
    "from": "07/17/2026 - Everett Rattray x Richard Claessen KFS",
    "to": "07/17/2026 - Everett Rattray x Richard Claessen KFS \u2014 Closed"
  },
  {
    "id": "1TDLVQl7MQcmQYNXnVcMsWk-BfrU2wNio",
    "from": "07/17/2026 - Fabien COLLEC x Richard Claessen",
    "to": "07/17/2026 - Fabien COLLEC x Richard Claessen \u2014 Closed"
  },
  {
    "id": "1ZUP78ALXd4kgrVtvwxtejmRZToodJeiX",
    "from": "07/17/2026 - Impromptu Zoom Meeting",
    "to": "07/17/2026 - Impromptu Zoom Meeting (Maria Papasavvad) \u2014 Lost"
  },
  {
    "id": "1JAFI_5xasNP7AJhWhv5EwKqzR5WDIJLG",
    "from": "07/17/2026 - Impromptu Zoom Meeting",
    "to": "07/17/2026 - Impromptu Zoom Meeting (Ryan) \u2014 Lost"
  },
  {
    "id": "1Gc0DgvEnSL2hkOUScEBumQQTr8jopedi",
    "from": "07/18/2026 - Impromptu Zoom Meeting",
    "to": "07/18/2026 - Impromptu Zoom Meeting (Dale H.) \u2014 Follow Up"
  },
  {
    "id": "1hJoer6WKegs0nsAqJYcNw97ah0IgLpWF",
    "from": "07/18/2026 - Impromptu Zoom Meeting",
    "to": "07/18/2026 - Impromptu Zoom Meeting (Pete Vazquez) \u2014 Follow Up"
  },
  {
    "id": "1F1Cvc44BxjAlSVhARWgvG8L2qK5a7BQm",
    "from": "07/18/2026 - Impromptu Zoom Meeting",
    "to": "07/18/2026 - Impromptu Zoom Meeting (Ryan Mitchell) \u2014 Follow Up"
  },
  {
    "id": "1CXml1kQmGKQl7i0VbQsmS1ojGE-ETwfN",
    "from": "07/18/2026 - Impromptu Zoom Meeting",
    "to": "07/18/2026 - Impromptu Zoom Meeting (Tyron Giuliani) \u2014 Follow Up"
  },
  {
    "id": "1u18mFTgISG9d4aQo7PqoAX4-UpJshMhf",
    "from": "07/20/2026 - Impromptu Zoom Meeting",
    "to": "07/20/2026 - Impromptu Zoom Meeting (Brett Weil) \u2014 Follow Up"
  },
  {
    "id": "1zV7TMHQhmrwhzz3vVgAGDIcxZMgJTOo9",
    "from": "07/20/2026 - Impromptu Zoom Meeting",
    "to": "07/20/2026 - Impromptu Zoom Meeting (Chad) \u2014 Lost"
  },
  {
    "id": "1Zs19-sGi6_-saLT7GcLVB3EeRCcx0VqT",
    "from": "07/21/2026 - Impromptu Zoom Meeting",
    "to": "07/21/2026 - Impromptu Zoom Meeting (Daniel) \u2014 Lost"
  },
  {
    "id": "15o6A6zV4g31v1a0ljoOqXSQs0Y840rNC",
    "from": "07/21/2026 - Impromptu Zoom Meeting",
    "to": "07/21/2026 - Impromptu Zoom Meeting (Declan Grund) \u2014 Lost"
  },
  {
    "id": "1qK4s6Xi2c5zbu6AU_LNVvXc3mc_RULcV",
    "from": "07/21/2026 - Impromptu Zoom Meeting",
    "to": "07/21/2026 - Impromptu Zoom Meeting (Ethan Kyllo) \u2014 Lost"
  },
  {
    "id": "17CuDTPpvGUVlZWO6ilKijN19DZl7orM1",
    "from": "07/21/2026 -  Giulian Carcioppolo x Richard Claessen",
    "to": "07/21/2026 -  Giulian Carcioppolo x Richard Claessen \u2014 Follow Up"
  },
  {
    "id": "1kLEaDyLaRBfYBN5hPBqbdfNQCAx8NPCw",
    "from": "07/22/2026 - Impromptu Zoom Meeting",
    "to": "07/22/2026 - Impromptu Zoom Meeting (Ansur Ahmed) \u2014 Follow Up"
  },
  {
    "id": "10ddtGFz4GVsuhTroyr67yz2ttSpltQSU",
    "from": "07/22/2026 - Impromptu Zoom Meeting",
    "to": "07/22/2026 - Impromptu Zoom Meeting (Brian) \u2014 Lost"
  },
  {
    "id": "1-hdO2rjbw7Mnf1cItwG0LpmD4jm7Fmtd",
    "from": "07/22/2026 - Impromptu Zoom Meeting",
    "to": "07/22/2026 - Impromptu Zoom Meeting (Daniel Borunda) \u2014 Follow Up"
  },
  {
    "id": "1Iw53-aYQtKzgWs29KUBDb50EL66zniea",
    "from": "07/22/2026 - Pete Vazquez x Richard",
    "to": "07/22/2026 - Pete Vazquez x Richard \u2014 Closed"
  },
  {
    "id": "1lqQeDcl5cqnURWYL0C3xwBZTDgiDWnNM",
    "from": "07/22/2026 - Impromptu Zoom Meeting",
    "to": "07/22/2026 - Impromptu Zoom Meeting (Pukar Patel) \u2014 Follow Up"
  },
  {
    "id": "1ipfRLmdc0shn7D1q5p38CUPXuJ2-wtt9",
    "from": "07/22/2026 - Impromptu Zoom Meeting",
    "to": "07/22/2026 - Impromptu Zoom Meeting (Ricky) \u2014 Follow Up"
  },
  {
    "id": "1PnJs1UGQJVBwxOL8gcUFQDMbHDB-m9LY",
    "from": "07/22/2026 - Impromptu Zoom Meeting",
    "to": "07/22/2026 - Impromptu Zoom Meeting (Rob) \u2014 Follow Up"
  },
  {
    "id": "1s9N04szcx8yzthTP61-ZcAixEfQLdu_I",
    "from": "07/23/2026 - Impromptu Zoom Meeting",
    "to": "07/23/2026 - Impromptu Zoom Meeting (Beau Paschall) \u2014 Closed"
  },
  {
    "id": "1hktapp6GBdw_-Qbgc4hKltz0ojq_nepk",
    "from": "07/23/2026 - Impromptu Zoom Meeting",
    "to": "07/23/2026 - Impromptu Zoom Meeting (Bennu Kham Ra Ankh Aten) \u2014 Follow Up"
  },
  {
    "id": "1rupZpLXxTzBaGu5Kh4uHkhPOL257hPzK",
    "from": "07/23/2026 - Impromptu Zoom Meeting",
    "to": "07/23/2026 - Impromptu Zoom Meeting (Emanuel Sol\u00eds) \u2014 Closed"
  },
  {
    "id": "12BVUfL0uyBeFT5i56Imh5Li1XGT6phxr",
    "from": "07/23/2026 - Impromptu Zoom Meeting",
    "to": "07/23/2026 - Impromptu Zoom Meeting (Joseph) \u2014 Closed"
  },
  {
    "id": "1QRuOSGtVJfCI0b4EwniYCd5RTqAP1at0",
    "from": "07/23/2026 - Robyn Stillwater x  Andrew Musial",
    "to": "07/23/2026 - Robyn Stillwater x  Andrew Musial \u2014 Closed"
  },
  {
    "id": "1IcDvWg2lZiWELhmE3HZTBYcwqzdmChUX",
    "from": "07/24/2026 - Giulian Carcioppolo x Richard Claessen",
    "to": "07/24/2026 - Giulian Carcioppolo x Richard Claessen \u2014 Lost"
  },
  {
    "id": "1D7De27LIX_odi1R3T4cwFg03CswW4R0s",
    "from": "07/24/2026 - Joe Ferretti and Richard Claessen - Gameplan ",
    "to": "07/24/2026 - Joe Ferretti and Richard Claessen - Gameplan \u2014 Follow Up"
  },
  {
    "id": "1WO_s1Mt3GtUGEAPTTIQlW1QFbRrdqKFL",
    "from": "07/24/2026 - Impromptu Zoom Meeting",
    "to": "07/24/2026 - Impromptu Zoom Meeting (Kitch Cash) \u2014 Closed"
  },
  {
    "id": "1I_TE97QE5J8cN-c-s5I8Vi7oFWYz21Of",
    "from": "07/24/2026 - Impromptu Zoom Meeting",
    "to": "07/24/2026 - Impromptu Zoom Meeting (Nik Howe) \u2014 Follow Up"
  },
  {
    "id": "1aixGcNV4QFmEyG3-5qT9QfeB0puII5p-",
    "from": "07/24/2026 - Impromptu Zoom Meeting",
    "to": "07/24/2026 - Impromptu Zoom Meeting (Patrick Dominguez) \u2014 Closed"
  },
  {
    "id": "1HAWGhjVcDVtTI90y-gE8_a3O9NHxvAth",
    "from": "07/25/2026 - Impromptu Zoom Meeting",
    "to": "07/25/2026 - Impromptu Zoom Meeting (Jimin Bhuptani) \u2014 Follow Up"
  },
  {
    "id": "1xZ-WpZ8vTyhTUJzSO6edbk9a529i_3me",
    "from": "07/25/2026 - Impromptu Zoom Meeting",
    "to": "07/25/2026 - Impromptu Zoom Meeting (Scott Hamilton) \u2014 Closed"
  },
  {
    "id": "1XKQ3GzoY7WnlGuBntSUwsMvrGBBsRqT4",
    "from": "07/26/2026 - Impromptu Zoom Meeting",
    "to": "07/26/2026 - Impromptu Zoom Meeting (Edward Garcia) \u2014 Follow Up"
  },
  {
    "id": "1-IRS60Op7qMOr53cHTW0d4MVGC6xomDi",
    "from": "07/26/2026 - Impromptu Zoom Meeting",
    "to": "07/26/2026 - Impromptu Zoom Meeting (Geoffrey) \u2014 Follow Up"
  },
  {
    "id": "1pssnTO9n45lIaXcHs7CaiASz67EM3L-_",
    "from": "07/26/2026 - Impromptu Zoom Meeting",
    "to": "07/26/2026 - Impromptu Zoom Meeting (Omar) \u2014 Follow Up"
  },
  {
    "id": "1sjfq9LHMjf2FsgvraMts590Q_27IrQzK",
    "from": "07/26/2026 - Impromptu Zoom Meeting",
    "to": "07/26/2026 - Impromptu Zoom Meeting (Rudolph) \u2014 Follow Up"
  },
  {
    "id": "1Pgt6N9qwMJbDKhsdhjluV7oEZYg2z2PD",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Angelo) \u2014 Follow Up"
  },
  {
    "id": "1B4haVua5t3DpFVWIvSztrjLjwIRNppzw",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Arturo) \u2014 Follow Up"
  },
  {
    "id": "1ILPXJvgqOglaJgnMkQtP9NJjBMYG5a4v",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Chase R) \u2014 Follow Up"
  },
  {
    "id": "1mDRzOmKgetfC-sauh3nONAhDXfQEZ4Nk",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (David Pasco) \u2014 Follow Up"
  },
  {
    "id": "1uyJ3yn3GuuFfdh58mERmXN8GbberQnFi",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Erik Seman) \u2014 Closed"
  },
  {
    "id": "1P-rI2EwekW1obYvcC-2LCuaOnQXgxB91",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Javier) \u2014 Closed"
  },
  {
    "id": "1ynZ-xrObjAy-8jQWdX_nfHZb-fkqcyFq",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Richard Kellis) \u2014 Lost"
  },
  {
    "id": "1pzrfwNoObSE1vMJHQFoJ6Oy17FPER4cw",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Rick Tuha) \u2014 Closed"
  },
  {
    "id": "1mDRzOmKgetfC-sauh3nONAhDXfQEZ4Nk",
    "from": "07/27/2026 - Impromptu Zoom Meeting",
    "to": "07/27/2026 - Impromptu Zoom Meeting (Yannick) \u2014 Follow Up"
  },
  {
    "id": "1oxNiRmIOwcosKiLMinQ95tAXnKyGxQJ9",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Alex Shivelhood) \u2014 Follow Up"
  },
  {
    "id": "1L9M5VsFH2WvFoHge8EQOxsJi7lnvIBbQ",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Casey) \u2014 Closed"
  },
  {
    "id": "1rDpmlT76DG3nY6qA9uMB4ELgrRJMHzo5",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Eddy) \u2014 Follow Up"
  },
  {
    "id": "1MBv9rBier2bCxCJDCst30IbT8FbUNIh0",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Istvan) \u2014 Closed"
  },
  {
    "id": "1SrNxZbxEjymvilw2Oc2df7t-xOWo-i2M",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Jeffrey Silver) \u2014 Follow Up"
  },
  {
    "id": "1Y-cQ7PUvJIybrdLiKe5odeVdrkVts__V",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Jeffrey Silver) \u2014 Closed"
  },
  {
    "id": "12XPf-PAYGNqNUPvIY4Su-XEXLUi4A7la",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Montana Butsch) \u2014 Follow Up"
  },
  {
    "id": "1AvGi1HRmVL1saO1zlco0r0axHHUenxtm",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (smanian) \u2014 Follow Up"
  },
  {
    "id": "1IJsweM8xAclkwlR9fEYfKmJXT0HRjoH_",
    "from": "07/28/2026 - Impromptu Zoom Meeting",
    "to": "07/28/2026 - Impromptu Zoom Meeting (Vimal) \u2014 Follow Up"
  },
  {
    "id": "1A1HDl-oM8KGCWyPaPXvA1TRHQFKavYJ2",
    "from": "07/29/2026 - Alex Shivelhood x Richard Claessen DH",
    "to": "07/29/2026 - Alex Shivelhood x Richard Claessen DH \u2014 Follow Up"
  },
  {
    "id": "1SUW9AD2aD9K9j7dfw93dWtouV7UIueQ1",
    "from": "07/29/2026 - Impromptu Zoom Meeting",
    "to": "07/29/2026 - Impromptu Zoom Meeting (Jorge Louren\u00e7o) \u2014 Follow Up"
  },
  {
    "id": "1Fwclm6pE87cOIhcXBtSgVBls_FNnV4WT",
    "from": "07/29/2026 - Impromptu Zoom Meeting",
    "to": "07/29/2026 - Impromptu Zoom Meeting (Marcus Mahar) \u2014 Closed"
  },
  {
    "id": "1WuvwDXbRj33GF8vKW4OlCZBx3bUjC9Us",
    "from": "07/29/2026 - Impromptu Zoom Meeting",
    "to": "07/29/2026 - Impromptu Zoom Meeting (Michael Critzer) \u2014 Lost"
  },
  {
    "id": "1f1LXc0NWQzLf800OVUFJQFKZ_uxz3L8x",
    "from": "07/29/2026 - Impromptu Zoom Meeting",
    "to": "07/29/2026 - Impromptu Zoom Meeting (Michael Galvan) \u2014 Closed"
  },
  {
    "id": "1Cl--a15_iXokj49hVTG4dvNEauhF_aWj",
    "from": "07/29/2026 - Impromptu Zoom Meeting",
    "to": "07/29/2026 - Impromptu Zoom Meeting (Sean Feeney) \u2014 Follow Up"
  },
  {
    "id": "1aKsLO60rJ5rRFpYkBNFR7BIxOT8YgohY",
    "from": "07/30/2026 - Impromptu Zoom Meeting",
    "to": "07/30/2026 - Impromptu Zoom Meeting (Dhairya Nanda) \u2014 Closed"
  },
  {
    "id": "1WAFZkUhGPNnICVmvSg3LP4JxvKZOCZFL",
    "from": "07/30/2026 - Impromptu Zoom Meeting",
    "to": "07/30/2026 - Impromptu Zoom Meeting (Francisco Adain Vega) \u2014 Closed"
  },
  {
    "id": "1u2K4wD-NNYe2ByQHlFosjeEN9p3VuBvT",
    "from": "07/30/2026 - Impromptu Zoom Meeting",
    "to": "07/30/2026 - Impromptu Zoom Meeting (Jeff Honigstock) \u2014 Follow Up"
  },
  {
    "id": "1DUQTGlFnlZlm5Bz5g3E-MPz14v5j9dLL",
    "from": "07/30/2026 - Impromptu Zoom Meeting",
    "to": "07/30/2026 - Impromptu Zoom Meeting (Kevin Vibert) \u2014 Follow Up"
  },
  {
    "id": "1dZhN54S0hUuiNUomI7aSo3ruVkvQOyQb",
    "from": "07/30/2026 - Impromptu Zoom Meeting",
    "to": "07/30/2026 - Impromptu Zoom Meeting (Lance Mardian) \u2014 Lost"
  },
  {
    "id": "1gR74xh1Ie4-m6IcfH2pwssuxhHZR9i4E",
    "from": "07/30/2026 - Impromptu Zoom Meeting",
    "to": "07/30/2026 - Impromptu Zoom Meeting (Michael Hogan) \u2014 Follow Up"
  },
  {
    "id": "19hyAj4TlAGYJn59ElHMZXjOSDY8kedAp",
    "from": "07/31/2026 - Impromptu Zoom Meeting",
    "to": "07/31/2026 - Impromptu Zoom Meeting (Rohan Bhatnagar) \u2014 Closed"
  }
];

function dryRun()        { _process(false); }
function applyRenames()  { _process(true);  }

function _process(commit) {
  var ok = 0, skipped = 0, failed = 0;
  Logger.log(commit ? '=== APPLYING RENAMES ===' : '=== DRY RUN — no changes ===');
  for (var i = 0; i < RENAMES.length; i++) {
    var r = RENAMES[i];
    try {
      var file = DriveApp.getFileById(r.id);
      var now = file.getName();
      if (now === r.to) { skipped++; continue; }
      if (now !== r.from) {
        Logger.log('SKIP (title changed since manifest): ' + now);
        skipped++;
        continue;
      }
      if (commit) file.setName(r.to);
      Logger.log((commit ? 'RENAMED: ' : 'WOULD RENAME: ') + now + '  ->  ' + r.to);
      ok++;
    } catch (e) {
      Logger.log('FAILED ' + r.id + ': ' + e.message);
      failed++;
    }
  }
  Logger.log('--- ' + ok + ' processed, ' + skipped + ' skipped, ' + failed + ' failed ---');
}

function revertRenames() {
  var ok = 0, failed = 0;
  for (var i = 0; i < RENAMES.length; i++) {
    var r = RENAMES[i];
    try {
      var file = DriveApp.getFileById(r.id);
      if (file.getName() === r.to) { file.setName(r.from); ok++; }
    } catch (e) {
      Logger.log('REVERT FAILED ' + r.id + ': ' + e.message);
      failed++;
    }
  }
  Logger.log('--- reverted ' + ok + ', failed ' + failed + ' ---');
}
