#!/usr/bin/env python3
"""
Generate the Drive rename manifest and a runnable Apps Script.

The Drive integration available to this project is read-only for titles, so
renaming happens on the client's side. This produces two artifacts:

  data/rename_manifest.csv  — file_id, current_title, proposed_title, outcome
  docs/rename.gs            — Apps Script with the pairs embedded, ready to paste

The script is deliberately idempotent and reversible: it skips files already
carrying a suffix, and the CSV retains every original title so the operation
can be undone.
"""
import csv
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CALLS = ROOT / "data" / "calls"
CSV_OUT = ROOT / "data" / "rename_manifest.csv"
GS_OUT = ROOT / "docs" / "rename.gs"

SUFFIX = {
    "closed": "Closed",
    "follow_up": "Follow Up",
    "lost": "Lost",
    "undetermined": "Undetermined",
}
SEP = " — "          # em dash, matches the display_title convention


def build():
    rows = []
    for f in sorted(CALLS.glob("*.json")):
        rec = json.loads(f.read_text())
        src, out = rec.get("source", {}), rec.get("outcome", {})
        fid, title = src.get("drive_file_id"), src.get("original_title")
        disp = out.get("disposition")
        if not (fid and title and disp):
            continue
        label = SUFFIX.get(disp, disp)
        if SEP in title and title.rstrip().endswith(label):
            continue                                   # already applied

        # Untitled recordings say only "Impromptu Zoom Meeting". Appending an
        # outcome alone leaves them nearly as unusable as before, so inject the
        # prospect name we recovered from the transcript — parenthetically, so
        # the original title survives intact and the addition is obvious.
        stem = title.rstrip()
        prospect = rec.get("prospect", {}).get("name")
        named = rec.get("call", {}).get("prospect_named_in_title", True)
        if prospect and not named and prospect.lower() not in stem.lower():
            stem = f"{stem} ({prospect})"

        rows.append({
            "file_id": fid,
            "current_title": title,
            "proposed_title": f"{stem}{SEP}{label}",
            "outcome": disp,
            "confidence": out.get("confidence"),
            "rep": rec.get("rep", {}).get("name"),
            "call_date": rec.get("call", {}).get("date"),
        })
    return rows


APPS_SCRIPT = """/**
 * Primal Instinct — append call outcome to transcript filenames.
 *
 * Generated by src/build_rename_manifest.py. %(n)d files.
 *
 * HOW TO RUN
 *   1. script.google.com  →  New project
 *   2. Paste this whole file, replacing the default contents
 *   3. Run `dryRun` first. It logs every change WITHOUT touching anything.
 *   4. Read the log. If it looks right, run `applyRenames`.
 *   5. To undo, run `revertRenames`.
 *
 * You must be signed in as an account with edit rights on the transcripts
 * folder. The files are owned by info@primalinstinct.net — if you only have
 * view access, ask them to run it instead.
 *
 * Safe to re-run: files already carrying the suffix are skipped.
 */

var RENAMES = %(pairs)s;

function dryRun()        { _process(false); }
function applyRenames()  { _process(true);  }

function _process(commit) {
  var ok = 0, skipped = 0, failed = 0;
  Logger.log(commit ? '=== APPLYING RENAMES ===' : '=== DRY RUN — no changes ===');
  for (var i = 0; i < RENAMES.length; i++) {
    var r = RENAMES[i];
    try {
      var file = DriveApp.getFileById(r.id);
      var now = file.getName();
      if (now === r.to) { skipped++; continue; }
      if (now !== r.from) {
        Logger.log('SKIP (title changed since manifest): ' + now);
        skipped++;
        continue;
      }
      if (commit) file.setName(r.to);
      Logger.log((commit ? 'RENAMED: ' : 'WOULD RENAME: ') + now + '  ->  ' + r.to);
      ok++;
    } catch (e) {
      Logger.log('FAILED ' + r.id + ': ' + e.message);
      failed++;
    }
  }
  Logger.log('--- ' + ok + ' processed, ' + skipped + ' skipped, ' + failed + ' failed ---');
}

function revertRenames() {
  var ok = 0, failed = 0;
  for (var i = 0; i < RENAMES.length; i++) {
    var r = RENAMES[i];
    try {
      var file = DriveApp.getFileById(r.id);
      if (file.getName() === r.to) { file.setName(r.from); ok++; }
    } catch (e) {
      Logger.log('REVERT FAILED ' + r.id + ': ' + e.message);
      failed++;
    }
  }
  Logger.log('--- reverted ' + ok + ', failed ' + failed + ' ---');
}
"""


def main():
    rows = build()
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    GS_OUT.parent.mkdir(parents=True, exist_ok=True)

    with CSV_OUT.open("w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=["file_id", "current_title", "proposed_title",
                                           "outcome", "confidence", "rep", "call_date"])
        w.writeheader()
        w.writerows(rows)

    pairs = json.dumps([{"id": r["file_id"], "from": r["current_title"],
                         "to": r["proposed_title"]} for r in rows], indent=2)
    GS_OUT.write_text(APPS_SCRIPT % {"n": len(rows), "pairs": pairs})

    by_outcome = {}
    for r in rows:
        by_outcome[r["outcome"]] = by_outcome.get(r["outcome"], 0) + 1
    print(f"{len(rows)} renames staged")
    for k, v in sorted(by_outcome.items(), key=lambda x: -x[1]):
        print(f"  {k:14} {v}")
    print(f"\nWrote {CSV_OUT.relative_to(ROOT)}")
    print(f"Wrote {GS_OUT.relative_to(ROOT)}")
    low = [r for r in rows if (r["confidence"] or 1) < 0.7]
    if low:
        print(f"\n{len(low)} rename(s) rest on a low-confidence outcome (<0.70) — review these first:")
        for r in low[:10]:
            print(f"  {r['confidence']}  {r['proposed_title'][:78]}")


if __name__ == "__main__":
    main()
